import type { Theme } from '../../types';

export const postapoTheme: Theme = {
  id: 'postapo',
  name: 'Postapo',
  scope: 'both',
  atmosphere: 'Apokalyptická pustina — desaturovaná olivová + rez',
  vars: {
    '--bg-primary':       '#0c0c08',
    '--bg-secondary':     '#141410',
    '--bg-card':          '#1a1a14',
    '--bg-card-hover':    '#202018',
    '--accent':           '#8a8810',
    '--accent-bright':    '#a8a818',
    '--accent-dim':       '#484808',
    '--accent-soft':      'rgba(138, 136, 16, 0.18)',
    '--text-primary':     '#b0a888',
    '--text-secondary':   '#857b66',
    '--text-muted':       '#383830',
    '--border':           '#302e20',
    '--border-subtle':    '#1c1c14',
    '--border-strong':    '#7a3810',
    '--success':          '#6a8830',
    '--warning':          '#7a3810',
    '--danger':           '#9a4020',
    '--info':             '#5a7080',
    '--text-on-accent':       '#0c0c08',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(0, 0, 0, 0.7)',
    '--success-soft':         'rgba(106, 136, 48, 0.14)',
    '--success-soft-border':  'rgba(106, 136, 48, 0.4)',
    '--warning-soft':         'rgba(122, 56, 16, 0.16)',
    '--warning-soft-border':  'rgba(122, 56, 16, 0.4)',
    '--danger-soft':          'rgba(154, 64, 32, 0.14)',
    '--danger-soft-border':   'rgba(154, 64, 32, 0.4)',
    '--danger-focus-ring':    'rgba(154, 64, 32, 0.3)',
    '--font-logo':        '"Oswald", "Bebas Neue", sans-serif',
    '--font-display':     '"Roboto Condensed", "Oswald", sans-serif',
    '--font-body':        '"Roboto", "Source Sans Pro", sans-serif',
  },
  fonts: {
    logo: 'Oswald',
    display: 'Roboto Condensed',
    body: 'Roboto',
  },
  thumbnail: '/themes/thumbnails/postapo.webp',
  background: '/themes/backgrounds/postapo.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
