import type { Theme } from '@/themes/types';

export const vesmirnaBitvaTheme: Theme = {
  id: 'vesmirna-bitva',
  name: 'Vesmírná bitva',
  scope: 'both',
  atmosphere: 'Bojový alarm — červená, černá, urgence',
  vars: {
    '--bg-primary':       '#050305',
    '--bg-secondary':     '#0a0508',
    '--bg-card':          '#0f0508',
    '--bg-card-hover':    '#150810',
    '--accent':           '#c01818',
    '--accent-bright':    '#e02020',
    '--accent-dim':       '#600808',
    '--accent-soft':      'rgba(192, 24, 24, 0.18)',
    '--text-primary':     '#e0c0c0',
    '--text-secondary':   '#b06161',
    '--text-muted':       '#402020',
    '--border':           '#150808',
    '--border-subtle':    '#0a0404',
    '--border-strong':    '#c01818',
    '--success':          '#3ecf8e',
    '--warning':          '#e05010',
    '--danger':           '#e02020',
    '--info':             '#5ba4f5',
    '--text-on-accent':       '#ffffff',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(0, 0, 0, 0.75)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(224, 80, 16, 0.14)',
    '--warning-soft-border':  'rgba(224, 80, 16, 0.4)',
    '--danger-soft':          'rgba(224, 32, 32, 0.16)',
    '--danger-soft-border':   'rgba(224, 32, 32, 0.4)',
    '--danger-focus-ring':    'rgba(224, 32, 32, 0.3)',
    '--font-logo':        '"Orbitron", "Russo One", sans-serif',
    '--font-display':     '"Rajdhani", "Exo 2", sans-serif',
    '--font-body':        '"Roboto Condensed", "Roboto", sans-serif',
  },
  fonts: {
    logo: 'Orbitron',
    display: 'Rajdhani',
    body: 'Roboto Condensed',
  },
  thumbnail: '/themes/thumbnails/vesmirna-bitva.webp',
  background: '/themes/backgrounds/vesmirna-bitva.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
