import type { Theme } from '../../types';

export const severskeRunyTheme: Theme = {
  id: 'severske-runy',
  name: 'Severské runy',
  scope: 'both',
  atmosphere: 'Vikingský runový kámen — led, železo, pochodně',
  vars: {
    '--bg-primary':       '#080c10',
    '--bg-secondary':     '#0c1018',
    '--bg-card':          '#101520',
    '--bg-card-hover':    '#161e28',
    '--accent':           '#4ab0d0',
    '--accent-bright':    '#70d0f0',
    '--accent-dim':       '#205870',
    '--accent-soft':      'rgba(74, 176, 208, 0.16)',
    '--text-primary':     '#c8d8e8',
    '--text-secondary':   '#5888a8',
    '--text-muted':       '#304050',
    '--border':           '#3a4858',
    '--border-subtle':    '#202830',
    '--border-strong':    '#4ab0d0',
    '--success':          '#3ecf8e',
    '--warning':          '#c08030',
    '--danger':           '#c04040',
    '--info':             '#4ab0d0',
    '--text-on-accent':       '#04101a',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(0, 4, 8, 0.7)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(192, 128, 48, 0.16)',
    '--warning-soft-border':  'rgba(192, 128, 48, 0.4)',
    '--danger-soft':          'rgba(192, 64, 64, 0.14)',
    '--danger-soft-border':   'rgba(192, 64, 64, 0.4)',
    '--danger-focus-ring':    'rgba(192, 64, 64, 0.3)',
    '--font-logo':        '"Cinzel", "Norse", Georgia, serif',
    '--font-display':     '"Uncial Antiqua", "IM Fell English", Georgia, serif',
    '--font-body':        '"Lora", "EB Garamond", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel',
    display: 'Uncial Antiqua',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/severske-runy.webp',
  background: '/themes/backgrounds/severske-runy.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
