import type { Theme } from '../../types';

export const africkeTheme: Theme = {
  id: 'africke',
  name: 'Africké',
  scope: 'both',
  atmosphere: 'Africká savana — eben, amber, terracotta, kmenové vzory',
  vars: {
    '--bg-primary':       '#0e0804',
    '--bg-secondary':     '#160c06',
    '--bg-card':          '#1e1208',
    '--bg-card-hover':    '#261808',
    '--accent':           '#c8880a',
    '--accent-bright':    '#e8a820',
    '--accent-dim':       '#604008',
    '--accent-soft':      'rgba(200, 136, 10, 0.16)',
    '--text-primary':     '#d4a060',
    '--text-secondary':   '#9a733a',
    '--text-muted':       '#403018',
    '--border':           '#2a1808',
    '--border-subtle':    '#1a0c04',
    '--border-strong':    '#c8880a',
    '--success':          '#6a8830',
    '--warning':          '#c04818',
    '--danger':           '#a83838',
    '--info':             '#3060a0',
    '--text-on-accent':       '#0e0804',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(8, 4, 2, 0.7)',
    '--success-soft':         'rgba(106, 136, 48, 0.16)',
    '--success-soft-border':  'rgba(106, 136, 48, 0.4)',
    '--warning-soft':         'rgba(192, 72, 24, 0.14)',
    '--warning-soft-border':  'rgba(192, 72, 24, 0.4)',
    '--danger-soft':          'rgba(168, 56, 56, 0.16)',
    '--danger-soft-border':   'rgba(168, 56, 56, 0.4)',
    '--danger-focus-ring':    'rgba(168, 56, 56, 0.3)',
    '--font-logo':        '"Cinzel", "Trajan Pro", Georgia, serif',
    '--font-display':     '"IM Fell English", "Lora", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel',
    display: 'IM Fell English',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/africke.webp',
  background: '/themes/backgrounds/africke.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
