/**
 * 8.7h — DrD II kompletní katalog zvláštních schopností všech povolání.
 *
 * 1:1 přenos z `c:/Matrix/Matrix/frontend/src/components/diary/drd2Abilities.ts`
 * — 12 základních povolání × 12 ZS + 10 mistrovských × 12 ZS = 264 schopností.
 */

export interface AbilityDef {
  id: string;
  name: string;
  professionId: string;
  category: string;
  activation: string;
  isReservedSkill: boolean;
  requiresChoice: boolean;
  choiceLabel: string;
  summary: string;
}

const a = (
  pid: string,
  name: string,
  cat: string,
  act: string,
  sum: string,
  opts?: Partial<AbilityDef>,
): AbilityDef => ({
  id: `${pid}-${name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+$/, '')}`,
  name,
  professionId: pid,
  category: cat,
  activation: act,
  summary: sum,
  isReservedSkill: false,
  requiresChoice: false,
  choiceLabel: '',
  ...opts,
});

export const PROFESSION_ABILITIES: Record<string, AbilityDef[]> = {
  bojovnik: [
    a('bojovnik', 'Letící zbraň', 'bojová', 'aktivní', 'Práce s vrženou nebo letící zbraní v boji.'),
    a('bojovnik', 'Cit pro zbraň', 'bojová', 'specializace', 'Specializace na jednu konkrétní zbraň.', { requiresChoice: true, choiceLabel: 'Vybraná zbraň' }),
    a('bojovnik', 'Gladiátor', 'bojová', 'situační', 'Arénní boj, efektní manévry a tlak publika.'),
    a('bojovnik', 'Zápasník', 'bojová', 'fyzická', 'Zápas, chvaty, držení, srážení, přetlačování.'),
    a('bojovnik', 'Silák', 'fyzická', 'pasivní', 'Výjimečné silové výkony: zvedání, lámání, přetlačení.'),
    a('bojovnik', 'Šampión', 'sociálně-bojová', 'pasivní', 'Prestiž, respekt a soubojová autorita.'),
    a('bojovnik', 'Bojové reflexy', 'bojová', 'reakční', 'Rychlá reakce v boji, připravenost na přepadení.'),
    a('bojovnik', 'Osobní strážce', 'obranná', 'reakční', 'Ochrana jiné postavy, krytí spojence.'),
    a('bojovnik', 'Rameno na rameno', 'týmová', 'bojová', 'Lepší boj ve spolupráci, držení linie.'),
    a('bojovnik', 'Hlava nehlava', 'bojová', 'agresivní', 'Prudký, riskantní, agresivní útok.'),
    a('bojovnik', 'Pádný úder', 'bojová', 'aktivní', 'Silný rozhodující zásah, těžká rána.'),
    a('bojovnik', 'Přečtení soupeře', 'taktická', 'analytická', 'Odhad protivníka: styl, záměr, slabina.'),
  ],
  lovec: [
    a('lovec', 'Jedno oko otevřené', 'průzkumná', 'reakční', 'Ostražitost při hlídce, spánku nebo cestování.'),
    a('lovec', 'Vetřelci', 'průzkumná', 'situační', 'Vnímání narušitelů a stop cizí přítomnosti.'),
    a('lovec', 'Něco z ničeho', 'přežití', 'situační', 'Improvizace v divočině, provizorní vybavení.'),
    a('lovec', 'Dobrá muška', 'střelecká', 'pasivní', 'Přesnější střelba, míření, klidná ruka.'),
    a('lovec', 'Lučištník', 'střelecká', 'specializace', 'Specializace na luk nebo podobné střelné zbraně.'),
    a('lovec', 'Průzkumník', 'průzkumná', 'aktivní', 'Průzkum terénu, hledání bezpečné cesty.'),
    a('lovec', 'Zálesák', 'přežití', 'pasivní', 'Život v divočině, táboření, hledání potravy.'),
    a('lovec', 'Stopař', 'průzkumná', 'aktivní', 'Sledování stop lidí, zvířat nebo nestvůr.'),
    a('lovec', 'Krotitel', 'zvířata', 'sociální', 'Jednání se zvířaty, uklidnění, ochočení.', { requiresChoice: true, choiceLabel: 'Typ zvířete' }),
    a('lovec', 'Zdvojená střela', 'střelecká', 'aktivní', 'Rychlá nebo kombinovaná střelba.'),
    a('lovec', 'K neutahání', 'fyzická', 'pasivní', 'Výdrž při cestování a dlouhém pochodu.'),
    a('lovec', 'Jedna duše', 'zvířata', 'pasivní', 'Hluboké pouto se zvířecím společníkem.', { requiresChoice: true, choiceLabel: 'Zvíře / společník' }),
  ],
  kejklir: [
    a('kejklir', 'Změna tváře', 'klamání', 'aktivní', 'Vydávání se za jiný typ osoby bez převleku.', { isReservedSkill: true }),
    a('kejklir', 'Děsivá přesnost', 'bojová', 'specializace', 'Přesné vrhání konkrétním druhem vrhací zbraně.', { requiresChoice: true, choiceLabel: 'Vrhací zbraň' }),
    a('kejklir', 'Rychlé ruce', 'zlodějská', 'manuální', 'Kapsářství, triky, rychlé tasení.'),
    a('kejklir', 'Vrhač', 'bojová', 'střelecká', 'Specializace na vrhací zbraně.'),
    a('kejklir', 'Akrobat', 'pohybová', 'aktivní', 'Skoky, salta, pády, úniky.'),
    a('kejklir', 'Provazochodec', 'pohybová', 'situační', 'Rovnováha, pohyb po úzkých plochách.'),
    a('kejklir', 'Hadí muž', 'pohybová', 'úniková', 'Protahování, vyklouznutí, útěk z pout.'),
    a('kejklir', 'Zloděj', 'zlodějská', 'aktivní', 'Krádeže, odemykání, vybírání kapes.'),
    a('kejklir', 'Špeh', 'průzkumná', 'městská', 'Sledování, nenápadné naslouchání, infiltrace.'),
    a('kejklir', 'Komediant', 'sociální', 'herecká', 'Herectví, předstírání, stržení pozornosti.'),
    a('kejklir', 'Dvě mouchy jednou ranou', 'triková', 'aktivní', 'Trik řešící dvě věci najednou.'),
    a('kejklir', 'Skrytá kapsa', 'zlodějská', 'pasivní', 'Ukrytí drobných předmětů, pašování.'),
  ],
  mastickar: [
    a('mastickar', 'Čtení v duši', 'sociální', 'analytická', 'Odhad emocí, motivací, bolesti nebo lži.'),
    a('mastickar', 'Umění improvizace', 'léčivá', 'situační', 'Provizorní léčiva a improvizované postupy.'),
    a('mastickar', 'Všelék', 'léčivá', 'aktivní', 'Univerzální léčebný prostředek.'),
    a('mastickar', 'Neobvyklé jedy', 'jedy', 'výroba', 'Práce se zvláštními jedy a účinky.'),
    a('mastickar', 'Ranhojič', 'léčivá', 'aktivní', 'Ošetření zranění, stabilizace, léčba.'),
    a('mastickar', 'Travič', 'jedy', 'aktivní', 'Výroba, použití nebo rozpoznání jedů.'),
    a('mastickar', 'Vyjednavač', 'sociální', 'aktivní', 'Domluva, dohoda, uklidnění situace.'),
    a('mastickar', 'Ostrý jazyk', 'sociální', 'konfliktní', 'Slovní útok, urážka, psychologický tlak.'),
    a('mastickar', 'Moudrý rádce', 'podpůrná', 'pasivní', 'Pomoc radou, odhad situace.'),
    a('mastickar', 'Samaritán', 'léčivá', 'podpůrná', 'Obětavá péče, záchrana zraněného.'),
    a('mastickar', 'Pečovatelský zásah', 'léčivá', 'reakční', 'Rychlá pomoc ve scéně: ošetřit, stabilizovat.'),
    a('mastickar', 'Lazebník', 'léčivá', 'sociální', 'Péče o tělo, hygiena, léčebné služby.'),
  ],
  zarikavac: [
    a('zarikavac', 'Čarovné stráže', 'magie', 'aktivní', 'Vytváření magických strážců vázaných na obrazec.', { isReservedSkill: true }),
    a('zarikavac', 'Modlitby a uřknutí', 'magie', 'kletby', 'Požehnání a kletby přes slova a rituály.'),
    a('zarikavac', 'Knihomol', 'znalostní', 'magická', 'Práce s knihami, texty, symboly, záznamy.'),
    a('zarikavac', 'Zasvěcenec', 'společenská', 'magická', 'Napojení na řád, kult, tradici nebo školu.'),
    a('zarikavac', 'Divoký talent', 'magie', 'talent', 'Přirozený, instinktivní magický dar.'),
    a('zarikavac', 'Povolávač', 'magie', 'rituální', 'Volání bytostí, duchů nebo pomocníků.'),
    a('zarikavac', 'Bystrost', 'mentální', 'podpůrná', 'Zostřená mysl, rychlé pochopení.'),
    a('zarikavac', 'Spojení myslí', 'magie', 'psychická', 'Mentální napojení, sdílení myšlenek.'),
    a('zarikavac', 'Síla osobnosti', 'sociálně-magická', 'pasivní', 'Vůle, charisma, magická dominance.'),
    a('zarikavac', 'Mystický kruh', 'magie', 'obrazce', 'Práce s kruhy a rituálními hranicemi.'),
    a('zarikavac', 'Moc amuletu', 'magie', 'předmět', 'Rituální předmět jako nosič magické síly.', { requiresChoice: true, choiceLabel: 'Amulet / talisman' }),
    a('zarikavac', 'Věže a chrámy', 'magie', 'zázemí', 'Vazba na posvátná nebo magická místa.'),
  ],
  valecnik: [
    a('valecnik', 'Bojový výcvik', 'bojová', 'pasivní', 'Formální bojová průprava, vojenský dril, taktika a lepší využití zbraní.'),
    a('valecnik', 'Bohatýr', 'bojová', 'hrdinská', 'Nadlidsky působící hrdinský výkon v boji; vhodné pro silové a heroické scény.'),
    a('valecnik', 'Šermíř', 'bojová', 'specializace', 'Specializace na šerm, duel, přesnost, práci s čepelí.', { requiresChoice: true, choiceLabel: 'Zbraň / šermířský styl' }),
    a('valecnik', 'Veterán', 'bojová', 'zkušenost', 'Zkušenost z mnoha bitev; klid v konfliktu, odolnost proti panice, odhad bojiště.'),
    a('valecnik', 'Urozený', 'sociální', 'status', 'Válečník má společenskou váhu, původ nebo uznávané postavení.'),
    a('valecnik', 'Velitel', 'týmová', 'velitelská', 'Schopnost vést druhé v boji, dávat rozkazy, držet linii.'),
    a('valecnik', 'Válečný oř', 'jezdecká', 'vazba', 'Vazba na bojového koně nebo jezdecký boj.', { requiresChoice: true, choiceLabel: 'Kůň / jezdecký společník' }),
    a('valecnik', 'Válečný tanečník', 'bojová', 'pohybová', 'Pohyblivý bojový styl, elegance, rychlé manévry, boj v pohybu.'),
    a('valecnik', 'Hrdinský duch', 'morální', 'podpůrná', 'Nezlomnost, odvaha, inspirace pro druhé, schopnost ustát těžkou situaci.'),
    a('valecnik', 'Vůdcovské charisma', 'sociální', 'velitelská', 'Přirozené velení, působení na skupinu, respekt, motivace spojenců.'),
    a('valecnik', 'Popularita', 'sociální', 'pověst', 'Postava je známá, oblíbená nebo uznávaná mezi lidmi.'),
    a('valecnik', 'Slavné jméno', 'sociální', 'reputace', 'Reputace, která může otevírat dveře nebo zastrašovat protivníky.', { requiresChoice: true, choiceLabel: 'Přezdívka / titul' }),
  ],
  hranicar: [
    a('hranicar', 'Poutník', 'cestovní', 'pasivní', 'Dlouhé cesty, orientace, putování krajinou, odolnost na výpravách.'),
    a('hranicar', 'Dravčí instinkty', 'bojová', 'instinktivní', 'Rychlá reakce, lovecký instinkt, útok ve správný okamžik.'),
    a('hranicar', 'Berserk', 'bojová', 'stav', 'Zuřivý bojový stav, agresivní výpad, riskantní síla.'),
    a('hranicar', 'Drakobijce', 'bojová', 'proti nestvůrám', 'Specializace na boj s velkými a nebezpečnými nestvůrami.', { requiresChoice: true, choiceLabel: 'Typ nestvůry' }),
    a('hranicar', 'Čarostřelec', 'střelecká', 'zvláštní', 'Střelba s nadpřirozeným, zvláštním nebo mimořádně přesným efektem.'),
    a('hranicar', 'Strážce hranic', 'obranná', 'terénní', 'Ochrana hranice, průsmyku, stezky, osady nebo svěřeného území.'),
    a('hranicar', 'Slavný stvůrobijce', 'reputace', 'bojová', 'Reputace lovce nestvůr, autorita proti nadpřirozeným hrozbám.'),
    a('hranicar', 'Divý muž', 'přežití', 'osobnostní', 'Splynutí s divočinou, drsný život mimo civilizaci, nezkrotnost.'),
    a('hranicar', 'Hrr na ně!', 'týmová', 'bojová', 'Prudké povzbuzení k útoku, bojový pokřik, stržení družiny.'),
    a('hranicar', 'Lovec trofejí', 'lovecká', 'trofeje', 'Získávání a využívání trofejí z poražených tvorů.'),
    a('hranicar', 'Znalec krajiny', 'průzkumná', 'terénní', 'Výborná znalost terénu, cest, úkrytů, zkratek a nebezpečí.'),
    a('hranicar', 'Odhad kořisti', 'analytická', 'lovecká', 'Odhad síly, stop, chování a hodnoty lovené bytosti.'),
  ],
  saman: [
    a('saman', 'Čarovné nápoje', 'rituální', 'omamné látky', 'Příprava zvláštních nápojů, omamných nebo rituálních látek; šamanská alchymie, vize a změny vědomí.'),
    a('saman', 'Měnič podob', 'zvířecí magie', 'aktivní', 'Proměna v konkrétní druh zvířete.', { isReservedSkill: true, requiresChoice: true, choiceLabel: 'Zvolená zvířecí podoba' }),
    a('saman', 'Neviditelný jezdec', 'zvířecí magie', 'ovládání', 'Šamanské napojení na zvíře, možnost vést či ovlivňovat jeho pohyb a vnímání.'),
    a('saman', 'Vládce šelem', 'zvířata', 'dominance', 'Silnější působení na zvířata, autorita nad šelmami a divokými tvory.'),
    a('saman', 'Znak vlkodlaka', 'znak', 'zvířecí magie', 'Šamanský znak související s dravostí, proměnou, smečkou nebo predátorskou silou.'),
    a('saman', 'Znak můry', 'znak', 'psychický efekt', 'Šamanský znak související se sny, nocí, neklidem, halucinací nebo neviděným pohybem.'),
    a('saman', 'Medicinman', 'léčivá', 'rituální', 'Léčení, rituální péče, duchovní medicína, práce s tělem i myslí.'),
    a('saman', 'Zvěropán', 'zvířata', 'pomocníci', 'Výrazná autorita nad zvířecími pomocníky; vhodné pro postavu s více zvířecími vazbami.'),
    a('saman', 'Velký hadač', 'věštění', 'analytická', 'Věštění, čtení znamení, výklad snů, rituální předvídání.'),
    a('saman', 'Vůdce smečky', 'týmová', 'zvířecí', 'Vedení skupiny, smečky nebo spojenců skrze instinkt a dominanci.'),
    a('saman', 'Bezmezná důvěra', 'vztahová', 'podpůrná', 'Posílená důvěra mezi šamanem a zvířetem nebo družinou.'),
    a('saman', 'Stopy zvěře', 'stopování', 'zvířata', 'Čtení stop, zvířecího chování, pohybu v krajině a loveckých znamení.'),
  ],
  druid: [
    a('druid', 'Paměť vody', 'přírodní magie', 'voda', 'Získávání dojmů, stop nebo informací skrze vodu; řeky, studny, déšť, jezera, krev nebo mlhu.'),
    a('druid', 'Paměť kamene', 'přírodní magie', 'kámen', 'Čtení minulosti, otisků a událostí uložených v kameni, skalách, stavbách nebo zemi.'),
    a('druid', 'Paměť dřeva', 'přírodní magie', 'dřevo', 'Čtení stop ze stromů, dřeva, kořenů, kůry, starých lesů nebo dřevěných předmětů.'),
    a('druid', 'Znak vodanoje', 'znak', 'voda', 'Magický znak spojený s vodou, proudy, hlubinami nebo vodními bytostmi.'),
    a('druid', 'Znak skalnika', 'znak', 'kámen', 'Magický znak spojený se skálou, kamenem, pevností a tíhou.'),
    a('druid', 'Znak lešije', 'znak', 'les', 'Magický znak lesa, stromů, houštin, kořenů a divoké zeleně.'),
    a('druid', 'Mlha a led', 'přírodní magie', 'voda-led', 'Kouzla chladu, mlhy, námrazy, skrytí, zpomalení nebo zhoršení orientace.'),
    a('druid', 'Skály a prach', 'přírodní magie', 'země', 'Působení na kámen, suť, prach, zeminu, sesuvy nebo tvrdý terén.'),
    a('druid', 'Kořeny a šlahouny', 'přírodní magie', 'rostliny', 'Ovládání rostlin, svazování, zpomalování, prorůstání nebo vytváření překážek.'),
    a('druid', 'Spodní proudy', 'přírodní magie', 'proudy', 'Práce se skrytými proudy vody, pohybem pod povrchem nebo neviditelným tlakem přírody.'),
    a('druid', 'Tíha země', 'přírodní magie', 'země', 'Ztížení pohybu, tlak země, gravitace, únava, uzemnění nebo sražení k zemi.'),
    a('druid', 'Hněv lesa', 'přírodní magie', 'ofenzivní', 'Agresivní obrana lesa, probuzení divočiny, útok větví, trnů, zvířat či přírodních sil.'),
  ],
  lupic: [
    a('lupic', 'Dotykový jed', 'jedy', 'aktivní', 'Použití jedu kontaktem; vhodné pro skryté otravy nebo nenápadný útok.'),
    a('lupic', 'Mistr klíčník', 'zlodějská', 'technická', 'Zámky, klíče, trezory, zamčené dveře, mechanické zabezpečení.'),
    a('lupic', 'Městské stíny', 'městská', 'plížení', 'Pohyb městem, skrývání v davu, únik uličkami, znalost temných koutů.'),
    a('lupic', 'Pavouk', 'pohybová', 'infiltrační', 'Lezení, pohyb po zdech, střechách, římsách a úzkých konstrukcích.'),
    a('lupic', 'Mechanik', 'technická', 'aktivní', 'Práce s mechanismy, pastmi, zařízeními, zámky a technickými předměty.'),
    a('lupic', 'Záškodník', 'sabotážní', 'aktivní', 'Sabotáž, ničení vybavení, narušení zásob, příprava škodící akce.'),
    a('lupic', 'Padělatel', 'sociálně-technická', 'výroba', 'Falešné listiny, pečeti, mince, podpisy, identity.'),
    a('lupic', 'Mordýř', 'bojová', 'vražedná', 'Smrtící přepadení, zákeřný útok, vražedná přesnost.'),
    a('lupic', 'Speciální výcvik', 'specializace', 'aktivní', 'Obecné pole pro zvláštní lupičský výcvik.', { requiresChoice: true, choiceLabel: 'Zaměření výcviku' }),
    a('lupic', 'Líčidla a masky', 'klamání', 'převlek', 'Převleky, maskování tváře, falešná identita.'),
    a('lupic', 'Jako blesk', 'reakční', 'pohybová', 'Rychlý pohyb, rychlá reakce, rychlý únik nebo rychlé provedení akce.'),
    a('lupic', 'Město jako na dlani', 'městská', 'znalostní', 'Znalost městského prostředí, čtvrtí, kontaktů, únikových cest.'),
  ],
  zved: [
    a('zved', 'Lesní přízrak', 'plížení', 'terénní', 'Nenápadný pohyb v lese, maskování, stopování bez odhalení.'),
    a('zved', 'Nouzové střely', 'střelecká', 'improvizace', 'Výroba nebo použití improvizovaných střel i při nedostatku vybavení.'),
    a('zved', 'Černá ovce', 'sociální', 'reputace', 'Postava je vyvrhel, psanec nebo někdo mimo společenský řád; pomáhá v podsvětí.'),
    a('zved', 'Nájezdník', 'bojová', 'přepadová', 'Přepady, rychlé útoky, partyzánský styl, útok ze zálohy.'),
    a('zved', 'Kapitán', 'velitelská', 'aktivní', 'Vedení skupiny zvědů, bandy, posádky nebo družiny v akci.'),
    a('zved', 'Šedá eminence', 'sociální', 'skrytý vliv', 'Skryté ovlivňování, zákulisní moc, manipulace, práce přes jiné lidi.'),
    a('zved', 'Zbojník', 'sociální', 'terénní', 'Lesní bandita, přepady cest, život mimo zákon, znalost zbojnického prostředí.'),
    a('zved', 'Přískokem vpřed', 'pohybová', 'bojová', 'Rychlý taktický pohyb vpřed, krytí vzdálenosti, přesun v boji.'),
    a('zved', 'Kamufláž', 'maskování', 'aktivní', 'Maskování sebe, výstroje nebo tábora.'),
    a('zved', 'Budu tě krýt', 'týmová', 'reakční', 'Krytí spojence, podpora střelbou nebo odvedení pozornosti.'),
    a('zved', 'Šeptanda', 'informační', 'sociální', 'Získávání informací z pověstí, drbů, neoficiálních zpráv.'),
    a('zved', 'Znalec podsvětí', 'městská', 'podsvětí', 'Orientace mezi zločinci, pašeráky, překupníky, špehy a kontakty.'),
  ],
  vedmak: [
    a('vedmak', 'Znamení Fehu', 'vědmácké znamení', 'aktivní', 'Vědmácké runové znamení; oheň, bohatství, útočný efekt.', { isReservedSkill: true }),
    a('vedmak', 'Znamení Othala', 'vědmácké znamení', 'aktivní', 'Vědmácké runové znamení; ochranné, poutací nebo rituální použití.', { isReservedSkill: true }),
    a('vedmak', 'Znamení Raidho', 'vědmácké znamení', 'podpůrná magie', 'Uklidňující / povzbuzující znamení, práce se strachem a Ohrožením při střetu s temnými bytostmi.', { isReservedSkill: true }),
    a('vedmak', 'Znamení Berkano', 'vědmácké znamení', 'obranná magie', 'Obranné znamení proti kouzlu mířenému na vědmáka.', { isReservedSkill: true }),
    a('vedmak', 'Znamení Tiwaz', 'vědmácké znamení', 'bojová magie', 'Urychlující znamení, bojová obrana a tělesné protiakce.', { isReservedSkill: true }),
    a('vedmak', 'Znak slunce', 'vědmácké znamení', 'obrazec', 'Magický obrazec, skrze který lze působit vědmáckými znameními.', { isReservedSkill: true }),
    a('vedmak', 'Stříbrná zbraň', 'bojová', 'specializace', 'Použití stříbrné zbraně proti nemrtvým, běsům a nadpřirozeným tvorům.', { requiresChoice: true, choiceLabel: 'Stříbrná zbraň' }),
    a('vedmak', 'Vymítač', 'specializace', 'znamení', 'Mistrovství v používání vědmáckých znamení.'),
    a('vedmak', 'Postrach přízraků', 'bojová', 'proti nemrtvým', 'Vědmák působí jako hrozba pro přízraky, nemrtvé a podobné entity.'),
    a('vedmak', 'Svatý hněv', 'magická', 'rozsáhlá', 'Rozšířené nebo skupinové použití vědmáckých znamení proti více cílům.'),
    a('vedmak', 'Zmutované tělo', 'fyzická', 'pasivní', 'Tělesná proměna, jizvy, mutace nebo fyzická úprava související s vědmáckou cestou.'),
    a('vedmak', 'Zrnko pravdy', 'znalostní', 'analytická', 'Schopnost najít pravdivé jádro v pověrách, legendách a příbězích o nestvůrách.'),
  ],
  alchymista: [
    a('alchymista', 'Živá voda', 'elixír', 'léčení', 'Léčivý nebo obnovující elixír; zázračné léčení, obnova a alchymistická podpora.'),
    a('alchymista', 'Mystický ranhojič', 'léčivá', 'alchymie', 'Magicky posílené léčení a práce s tělem pomocí rituálů nebo substancí.'),
    a('alchymista', 'Neobvyklé třaskaviny', 'výroba', 'výbušniny', 'Výroba výbušnin, zápalných látek a zvláštních destruktivních směsí.'),
    a('alchymista', 'Posílení elixíru', 'elixír', 'úprava', 'Zesílení účinku elixíru, vyšší síla, delší trvání nebo lepší efekt.'),
    a('alchymista', 'Pán golemů', 'umělý život', 'rituální', 'Umožňuje pracovat s více umělými bytostmi.', { isReservedSkill: true }),
    a('alchymista', 'Umělá duše', 'umělý život', 'rituální', 'Vytvoření inteligentnější umělé bytosti schopné mluvit a plnit úkoly.', { isReservedSkill: true, requiresChoice: true, choiceLabel: 'Jméno / typ umělé bytosti' }),
    a('alchymista', 'Mudrc', 'znalostní', 'alchymie', 'Učenost, výzkum, laboratorní znalosti, teorie substancí a rituálů.'),
    a('alchymista', 'Ohněstrůjce', 'výroba', 'oheň', 'Práce s ohněm, výbuchy, zápalnými směsmi a ničivými prostředky.'),
    a('alchymista', 'Výrobce elixírů', 'výroba', 'elixíry', 'Specializace na tvorbu elixírů a jejich praktické použití.'),
    a('alchymista', 'Stvořitel', 'specializace', 'umělý život', 'Mistrovství ve vytváření a ovládání umělých bytostí.'),
    a('alchymista', 'Tělesná stráž', 'ochranná', 'pomocník', 'Umělá nebo alchymisticky vytvořená ochrana; golemický ochránce.', { requiresChoice: true, choiceLabel: 'Typ strážce / golema' }),
    a('alchymista', 'Hračička', 'výroba', 'technická', 'Drobná zařízení, mechanismy, hračky, alchymistické pomůcky a technické triky.'),
  ],
  carodej: [
    a('carodej', 'Dračí dech', 'magie ohně', 'útok', 'Ohnivý nebo žhavý ničivý projev; útok plamenem, žárem nebo výdechem.'),
    a('carodej', 'Síla vichřice', 'magie větru', 'útok', 'Prudký vítr, odhození, tlak vzduchu, pohyb předmětů nebo sražení cíle.'),
    a('carodej', 'Věčný žár', 'magie ohně', 'trvání', 'Delší trvání ohně, žáru, doutnání nebo zapálení.'),
    a('carodej', 'Kvílení meluzíny', 'magie větru', 'psychický efekt', 'Zvuk, vítr, strach, rozrušení, tlak bouře nebo narušení soustředění.'),
    a('carodej', 'Znak salamandra', 'magický obrazec', 'aktivní', 'Ohnivý magický obrazec pro působení ohnivou magií.', { isReservedSkill: true }),
    a('carodej', 'Znak sylfy', 'magický obrazec', 'aktivní', 'Větrný magický obrazec pro vzdušné působení.', { isReservedSkill: true }),
    a('carodej', 'Pán ohně', 'specializace', 'magie ohně', 'Mistrovství v ohnivých kouzlech a jejich lámání.'),
    a('carodej', 'Vládce větru', 'specializace', 'magie větru', 'Mistrovství ve větrných kouzlech a jejich lámání.'),
    a('carodej', 'Plamenné peklo', 'magie ohně', 'plošná magie', 'Rozsáhlé ohnivé kouzlo působící na skupinu cílů.'),
    a('carodej', 'Vzdušný vír', 'magie větru', 'plošná', 'Rozsáhlý nebo silný vír vzduchu, odhození, krytí, překážka či rozptýlení.'),
    a('carodej', 'Magický štít', 'obranná magie', 'aktivní', 'Ochrana proti útokům, kouzlům nebo živelnému působení.'),
    a('carodej', 'Společnost démonů', 'démonická', 'vztahová', 'Vazba na démony, jejich přítomnost, pomoc, rizika nebo magické kontakty.'),
  ],
  mag: [
    a('mag', 'Mámení smyslů', 'iluze', 'smysly', 'Ovlivnění vnímání cíle: zrak, sluch, čich, klamné dojmy.'),
    a('mag', 'Přeludy', 'iluze', 'aktivní', 'Vytváření iluzorních obrazů, klamných scén nebo falešných vjemů.'),
    a('mag', 'Neviditelný loutkář', 'manipulace', 'mysl', 'Skryté ovlivňování chování, nenápadná manipulace, tahání za nitky.'),
    a('mag', 'Požírač duší', 'psychická magie', 'temná', 'Temné působení na duši, vůli, psychiku nebo životní sílu.'),
    a('mag', 'Znak fantóma', 'znak', 'iluze', 'Magický znak související s iluzemi, přízraky nebo nehmotným projevem.'),
    a('mag', 'Znak upíra', 'znak', 'temná magie', 'Magický znak související s vysáváním, vůlí, strachem nebo ovládnutím.'),
    a('mag', 'Odhodlaná mysl', 'obranná', 'mentální', 'Obrana proti mentálnímu tlaku, pevná vůle, soustředění.'),
    a('mag', 'Podivný přítelíček', 'pomocník', 'zvláštní', 'Zvláštní společník, přízrak, iluzorní pomocník nebo neklidná entita.', { requiresChoice: true, choiceLabel: 'Typ přítelíčka / entity' }),
    a('mag', 'Lamač vůlí', 'manipulace', 'vůle', 'Přímé lámání odporu, donucení, psychický nátlak.'),
    a('mag', 'Vládce iluzí', 'specializace', 'iluze', 'Mistrovství v iluzorních kouzlech a jejich lámání.'),
    a('mag', 'Armáda přízraků', 'iluze', 'rozsáhlá', 'Vytváření více iluzorních nebo přízračných projevů najednou.'),
    a('mag', 'Davová psychóza', 'psychická magie', 'davová', 'Působení na skupinu lidí, šíření strachu, hysterie nebo falešného přesvědčení.'),
  ],
};

export const MASTER_ABILITIES: Record<string, AbilityDef[]> = {
  cernokneznik: [
    a('cernokneznik', 'Brány podsvětí', 'temná magie', 'rituální', 'Vyvolávání nemrtvých, běsů nebo bytostí ze snového světa.'),
    a('cernokneznik', 'Krvavá daň', 'temná magie', 'aktivní', 'Síla získaná proléváním krve protivníka.'),
    a('cernokneznik', 'Morová rána', 'temná magie', 'aktivní', 'Vytváření nákaz, ohnisek nemocí nebo výbušných mrtvých těl.', { isReservedSkill: true }),
    a('cernokneznik', 'Nekrolog', 'temná magie', 'rituální', 'Komunikace s mrtvými, čtení paměti zemřelých nebo přivolání duše.'),
    a('cernokneznik', 'Poslední vzpomínka', 'temná magie', 'analytická', 'Z krve oběti vyčte poslední okamžiky a někdy i tvář původce.'),
    a('cernokneznik', 'Spoutaná duše', 'temná magie', 'kletba', 'Prokletí navazující duši po smrti na nemrtvý stav.'),
    a('cernokneznik', 'Stíny noci', 'psychická', 'temná', 'Vytahuje ze strachu oběti temné projevy a působí psychický tlak.'),
    a('cernokneznik', 'Temné mysli', 'ovládání', 'aktivní', 'Ovlivňování mysli nemrtvých a běsů.'),
    a('cernokneznik', 'Temnozem', 'temná magie', 'pasivní', 'Na místech smrti získává silnější symbolický dosah.'),
    a('cernokneznik', 'Vládce duší', 'temná magie', 'rituální', 'Přenos duše do mrtvého těla, předmětu, rostliny nebo jiné schránky.'),
    a('cernokneznik', 'Zástup loutek', 'ovládání', 'pasivní', 'Udržení působení mysli nebo zvířecí magie i bez stálého dohledu.'),
    a('cernokneznik', 'Znesvěcení', 'temná magie', 'rituální', 'Uzavření či znesvěcení magického zřídla a vytvoření klíče k jeho síle.'),
  ],
  divotvurce: [
    a('divotvurce', 'Mistr lučby', 'výroba', 'aktivní', 'Přeměňuje nouzové suroviny na plnohodnotné.'),
    a('divotvurce', 'Nadhled', 'taktická', 'reakční', 'Na okamžik zastaví čas pro zhodnocení situace a snížení Ohrožení.'),
    a('divotvurce', 'Nicota', 'destruktivní magie', 'aktivní', 'Všeničící magie ignorující běžnou ochranu.'),
    a('divotvurce', 'Pán obrazců', 'magické obrazce', 'aktivní', 'Ovládá více magických obrazců a může tvořit dlouhodobé strážce.', { isReservedSkill: true }),
    a('divotvurce', 'Portál', 'magické obrazce', 'rituální', 'Vytváří propojené portálové obrazce pro přenos vjemů nebo bytostí.', { isReservedSkill: true }),
    a('divotvurce', 'Runotepec', 'výroba', 'rituální', 'Vyrábí runové předměty podobné trvalejší formě elixírů.'),
    a('divotvurce', 'Skrytá kouzla', 'magie', 'aktivní', 'Maskuje sesílání kouzel a jejich původ.'),
    a('divotvurce', 'Tkadlec snů', 'psychická', 'rituální', 'Přetváří snový svět a vstupuje do snů lidí či zvířat.'),
    a('divotvurce', 'Věčná kouzla', 'magie', 'rituální', 'Vytváří kouzla s dlouhodobým až trvalým působením.', { isReservedSkill: true }),
    a('divotvurce', 'Vládce rituálů', 'rituální', 'pasivní', 'Umožňuje používat více rituálních předmětů.'),
    a('divotvurce', 'Zakletí', 'proměna', 'aktivní', 'Proměňuje cíl do neškodné zvířecí podoby do splnění podmínky.'),
    a('divotvurce', 'Zloděj obrazců', 'magické obrazce', 'aktivní', 'Přebírá cizí magické obrazce a mění jejich typ.'),
  ],
  inkvizitor: [
    a('inkvizitor', 'Jasnozřivost', 'věštění', 'reakční', 'Záblesky budoucnosti v konfliktu, rychlá reakce a obrana.'),
    a('inkvizitor', 'Lámání kouzel', 'protimagie', 'aktivní', 'Umí lámat kouzla a obrazce různých magií.', { isReservedSkill: true }),
    a('inkvizitor', 'Magický rukopis', 'protimagie', 'analytická', 'Pozná původ, styl nebo autora kouzla.'),
    a('inkvizitor', 'Mučitel', 'výslech', 'aktivní', 'Znalost bolesti, nátlaku a výslechových metod.', { isReservedSkill: true }),
    a('inkvizitor', 'Ochranná aura', 'obranná magie', 'pasivní', 'Silná ochrana proti působení kouzel.'),
    a('inkvizitor', 'Paměť místa', 'věštění', 'aktivní', 'Z místa vyčte nejvypjatější událost posledního období.'),
    a('inkvizitor', 'Poklekni, lůzo!', 'sociální', 'aktivní', 'Autoritou zlomí protivníka a čerpá z jeho ponížení.'),
    a('inkvizitor', 'Špinavé metody', 'výslech', 'analytická', 'Určí slabinu protivníka pro výslech nebo nátlak.'),
    a('inkvizitor', 'Všemi mastmi mazaný', 'obranná', 'pasivní', 'Odolává přesvědčování, lstem, padělkům a manipulaci.'),
    a('inkvizitor', 'Výslech', 'výslech', 'aktivní', 'Nadání pro získávání pravdivých informací.', { isReservedSkill: true }),
    a('inkvizitor', 'Zpovědník', 'sociální', 'analytická', 'Zná hříchy a neřesti osob v organizaci a umí je využít.'),
    a('inkvizitor', 'Zrcadlení kouzel', 'protimagie', 'reakční', 'Obrací kouzla zpět proti sesilateli.'),
  ],
  mstitel: [
    a('mstitel', 'Bleskový pohyb', 'pohybová', 'reakční', 'Nadpřirozeně rychlé akrobatické pohyby a obrana zdarma.'),
    a('mstitel', 'Nekrytá místa', 'taktická', 'analytická', 'Odhalí slabiny protivníkovy zbroje.'),
    a('mstitel', 'Nervy z oceli', 'obranná', 'pasivní', 'Odolnost proti zastrašování a psychickému nátlaku.'),
    a('mstitel', 'Oči vzadu', 'průzkumná', 'reakční', 'Lépe reaguje na pasti, zálohy a útoky zezadu.'),
    a('mstitel', 'Sebeobrana', 'bojová', 'reakční', 'Obrací protivníkovu zbraň či útok proti jinému cíli.'),
    a('mstitel', 'Splynutí s davem', 'maskování', 'aktivní', 'Dokáže zmizet v davu i v organizované skupině.'),
    a('mstitel', 'Symbol smrti', 'psychická', 'aktivní', 'Vyděsí protivníka symbolem, výhružkou nebo znamením.'),
    a('mstitel', 'Utajení přítomnosti', 'maskování', 'aktivní', 'Skryje se před běžnými i nadpřirozenými smysly.'),
    a('mstitel', 'Vládce zmatku', 'týmová', 'aktivní', 'Vnáší chaos do nepřátelského oddílu.'),
    a('mstitel', 'Zadní vrátka', 'taktická', 'reakční', 'Při útoku si zároveň snižuje vlastní Ohrožení.'),
    a('mstitel', 'Zákeřné útoky', 'bojová', 'aktivní', 'Při překvapivém útoku není omezen počtem manévrů.'),
    a('mstitel', 'Zostření smyslu', 'smyslová', 'pasivní', 'Získá nebo posílí zvláštní smyslovou schopnost.', { requiresChoice: true, choiceLabel: 'Zvolený smysl' }),
  ],
  nicitel: [
    a('nicitel', 'Dračí jezdec', 'jezdecká', 'aktivní', 'Ovládání leteckých tvorů, letecký boj a akrobacie.', { requiresChoice: true, choiceLabel: 'Typ tvora' }),
    a('nicitel', 'Dračí řev', 'zastrašování', 'aktivní', 'Mistrovské zastrašování s krutými manévry.'),
    a('nicitel', 'Drakočlověk', 'proměna', 'aktivní', 'Proměna v dříve zabitého netvora.', { requiresChoice: true, choiceLabel: 'Zabitý netvor' }),
    a('nicitel', 'Legendární bojovník', 'bojová', 'pasivní', 'Ztěžuje protivníkům protiakce proti svým tělesným útokům.'),
    a('nicitel', 'Mystický lovec', 'bojová', 'střelecká', 'Boj zdálky proti nemrtvým a běsům.'),
    a('nicitel', 'Nebeský střelec', 'střelecká', 'jezdecká', 'Jízdní a letecký boj z dálky proti netvorům.'),
    a('nicitel', 'Ničivá smršť', 'bojová', 'aktivní', 'Zahlcení protivníka sérií ran v boji zblízka.'),
    a('nicitel', 'Ocelová pěst', 'bojová', 'aktivní', 'Ničivý neozbrojený nebo silový útok.'),
    a('nicitel', 'Ve zbroji jako doma', 'obranná', 'pasivní', 'Lepší využití zbroje a pohyb v ní.'),
    a('nicitel', 'Vozataj a lodivod', 'technická', 'aktivní', 'Mistrem v ovládání vozů, lodí a válečných prostředků.'),
    a('nicitel', 'Výsměch vítěze', 'sociálně-bojová', 'aktivní', 'Čerpá sílu ze svého vítězství a ponížení protivníka.'),
    a('nicitel', 'Záludné finty', 'bojová', 'taktická', 'Využívá bojové triky, finty a vnucování nevýhod protivníkovi.'),
  ],
  paladin: [
    a('paladin', 'Boží přízeň', 'posvátná', 'aktivní', 'Sesílá požehnání sám na sebe.'),
    a('paladin', 'Boží soud', 'posvátná', 'rituální', 'Vyvolá osudový souboj a omezí nečestné zásahy.', { isReservedSkill: true }),
    a('paladin', 'Posvátné místo', 'posvátná', 'rituální', 'Vytvoří nebo obnoví magické zřídlo v chrámu či kapli.', { isReservedSkill: true }),
    a('paladin', 'Přísaha', 'posvátná', 'rituální', 'Rituální slib dávající mimořádnou sílu při plnění cíle.', { requiresChoice: true, choiceLabel: 'Obsah přísahy' }),
    a('paladin', 'Rytíř světla', 'bojová', 'jezdecká', 'Mistrovský jízdní boj zblízka proti nemrtvým a běsům.'),
    a('paladin', 'Sebeobětování', 'léčivá', 'reakční', 'Převádí Jizvy druhých na sebe a zmírňuje je.'),
    a('paladin', 'Svatá slova', 'posvátná', 'aktivní', 'Mistrovské kletby a požehnání.'),
    a('paladin', 'Svatá zbroj', 'posvátná', 'rituální', 'Rituálně posílená zbroj proti temným tvorům.', { isReservedSkill: true }),
    a('paladin', 'Svěcená voda', 'výroba', 'rituální', 'Výroba látek působících na nemrtvé, oživené a běsy.'),
    a('paladin', 'Úsvit', 'posvátná', 'pasivní', 'Zářivá aura ztěžující činnost nemrtvým a běsům.'),
    a('paladin', 'Vnitřní zrak', 'smyslová', 'pasivní', 'Vidí obrysy nemrtvých a běsů, i skrytých či neviditelných.'),
    a('paladin', 'Žalář', 'posvátná', 'aktivní', 'Uvězní protivníka mimo čas a prostor.'),
  ],
  stin: [
    a('stin', 'Černý trh', 'městská', 'analytická', 'Určí, kdo v kraji vlastní hledaný obecný předmět.'),
    a('stin', 'Jak to ten skrček dělá?', 'průzkumná', 'aktivní', 'Odhadne plán budovy a dokáže se objevit za dveřmi.'),
    a('stin', 'Mistr útěků', 'úniková', 'reakční', 'Najde připravený únikový prostředek.'),
    a('stin', 'Pružiny a kolečka', 'technická', 'aktivní', 'Manipuluje s mechanismy bez náčiní nebo magickými gesty.', { isReservedSkill: true }),
    a('stin', 'Rozplynutí', 'obranná', 'reakční', 'Krátce se rozplyne a vyhne se fyzickému následku.'),
    a('stin', 'Rozsévač stínů', 'temná magie', 'reakční', 'Útočníka zasáhnou odvetné stíny.'),
    a('stin', 'Sabotáž', 'sabotážní', 'aktivní', 'Poškozuje nástroje, zbraně, zbroje a předměty.'),
    a('stin', 'Stínování', 'temná magie', 'aktivní', 'Napodobí protivníkovu dovednost temnou stínovou variantou.', { isReservedSkill: true }),
    a('stin', 'Temný ohař', 'stopování', 'pasivní', 'Sleduje směr k tomu, kdo jej zranil nebo koho zranil on.'),
    a('stin', 'Tichý společník', 'temná magie', 'rituální', 'Oživí vlastní stín jako samostatného pomocníka.'),
    a('stin', 'Zmizení ve stínech', 'maskování', 'aktivní', 'Stane se neodhalitelným ve stínu či přítmí.'),
  ],
  vudce: [
    a('vudce', 'Dle rozkazu!', 'velitelská', 'aktivní', 'Pomocníci nebo oddíly lépe plní připravený rozkaz.'),
    a('vudce', 'Intrikán', 'sociální', 'aktivní', 'Nadání pro intriky proti organizacím.'),
    a('vudce', 'Mistr a učitel', 'týmová', 'pasivní', 'Začlení se do oddílu a předává mu část svého mistrovství.'),
    a('vudce', 'Osobní garda', 'velitelská', 'pasivní', 'Levnější a kvalitnější pomocníci či oddíly z organizace.'),
    a('vudce', 'Posvátné pouto', 'vztahová', 'pasivní', 'Silnější vztah s pomocníky a lepší obnova Pouta.'),
    a('vudce', 'Příměří', 'sociální', 'reakční', 'Na okamžik zastaví konflikt a dá spojencům prostor.'),
    a('vudce', 'Přirozený šarm', 'sociální', 'pasivní', 'Ztěžuje protiakce proti svému vyjednávání.'),
    a('vudce', 'Sehranost', 'týmová', 'pasivní', 'Jako součást oddílu dává nadání v ovládaných dovednostech.'),
    a('vudce', 'Už jsem o vás slyšel', 'sociální', 'analytická', 'Určí oblíbené téma protivníka a využije ho v rozhovoru.'),
    a('vudce', 'Vládce jazyka', 'sociální', 'aktivní', 'Nadání pro vyjednávání, smlouvání a předstírání.', { isReservedSkill: true }),
    a('vudce', 'Vojevůdce', 'velitelská', 'aktivní', 'Nadání k vedení lidí v boji, mimo boj a válečnickým znalostem.'),
    a('vudce', 'Vůdce skupiny', 'velitelská', 'aktivní', 'Při snižování Ohrožení skupiny používá zdarma rozsáhle.'),
  ],
  zivlomag: [
    a('zivlomag', 'Bratr démonů', 'démonická', 'sociální', 'Živloví běsi jednají se živlomágem jako se sobě blízkým.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Clona', 'obranná', 'pasivní', 'Ochrana před nepohodlím a škodami svého živlu.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Džinova lampa', 'magie', 'rituální', 'Připoutá živlového pomocníka k předmětu.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Katastrofa', 'živelná magie', 'aktivní', 'Velmi rozsáhle zesílí existující projev svého živlu.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Nepřízeň živlů', 'živelná magie', 'kletba', 'Živel působí na cíle i kletbou a postihy.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Pán nebes', 'živelná magie', 'aktivní', 'Ovlivňuje nebeské jevy a počasí.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Řetězení', 'živelná magie', 'aktivní', 'Sesílá živelnou magii skrze spojence a pomocníky.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Síla přírody', 'živelná magie', 'pasivní', 'Čerpá výhodu z přirozeného projevu svého živlu v okolí.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Splynutí', 'živelná magie', 'proměna', 'Splyne se svým živlem a stane se jeho součástí.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Svolání běsů', 'démonická', 'rituální', 'Vyvolá běsy a netvory svého živlu jako pomocníky.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Vysátí', 'živelná magie', 'aktivní', 'Vysává živel z cíle a získává z toho sílu.', { requiresChoice: true, choiceLabel: 'Živel' }),
    a('zivlomag', 'Živelní pohroma', 'živelná magie', 'aktivní', 'Ztěžuje protiakce proti své živlové magii.', { requiresChoice: true, choiceLabel: 'Živel' }),
  ],
  zrec: [
    a('zrec', 'Baziliščí slina', 'jedy', 'výroba', 'Jedy a omamné látky působící i na netvory a běsy.'),
    a('zrec', 'Krajinář', 'přírodní magie', 'aktivní', 'Upraví či využije terén pro zvýšení Výhody družiny.'),
    a('zrec', 'Lesní strážci', 'přírodní magie', 'rituální', 'Vyvolá skupinu netvorů z přírodních podob.'),
    a('zrec', 'Listovlasý', 'proměna', 'aktivní', 'Promění se v rostlinu nebo zvířecího netvora.', { isReservedSkill: true, requiresChoice: true, choiceLabel: 'Podoba' }),
    a('zrec', 'Nápěv kůry a perutí', 'přírodní magie', 'aktivní', 'Nadání na kouzla při použití vhodného přírodního materiálu.'),
    a('zrec', 'Probuzení hvozdu', 'přírodní magie', 'aktivní', 'Zesílí magii dřeva nebo zvířecí magii k zabíjení či ovládnutí.'),
    a('zrec', 'Síla hvozdu', 'přírodní magie', 'rozsáhlá', 'Velmi rozsáhlá přírodní magie v oblasti.'),
    a('zrec', 'Smokův pařát', 'přírodní magie', 'aktivní', 'Kletby, požehnání a zvířecí magie působí i na netvory.'),
    a('zrec', 'Sněm lešijů', 'přírodní magie', 'rituální', 'Připoutá část duše k rostlině nebo místu a může se znovuzrodit.', { isReservedSkill: true }),
    a('zrec', 'Tajemství kořenů', 'přírodní magie', 'výroba', 'Tvoří neobvyklé rostliny a využívá přírodní zřídla.'),
    a('zrec', 'Volání rodu', 'zvířata', 'rituální', 'Přivolá zvolený druh zvířete nebo jeho skupinu.', { requiresChoice: true, choiceLabel: 'Druh zvířete' }),
    a('zrec', 'Vrabčí štěbetání', 'smyslová', 'aktivní', 'Přenese jeden svůj smysl na živou přírodní bytost nebo rostlinu.'),
  ],
};

/** Profession & master constants z `Drd2CharacterSheet.tsx`. */
export const BASIC_PROFESSIONS = [
  { id: 'bojovnik', name: 'Bojovník' },
  { id: 'lovec', name: 'Lovec' },
  { id: 'kejklir', name: 'Kejklíř' },
  { id: 'mastickar', name: 'Mastičkář' },
  { id: 'zarikavac', name: 'Zaříkávač' },
];

export const ADVANCED_PROFESSIONS: {
  id: string;
  name: string;
  requires: [string, string];
}[] = [
  { id: 'valecnik', name: 'Válečník', requires: ['bojovnik', 'kejklir'] },
  { id: 'hranicar', name: 'Hraničář', requires: ['bojovnik', 'lovec'] },
  { id: 'saman', name: 'Šaman', requires: ['lovec', 'mastickar'] },
  { id: 'druid', name: 'Druid', requires: ['lovec', 'zarikavac'] },
  { id: 'lupic', name: 'Lupič', requires: ['kejklir', 'mastickar'] },
  { id: 'zved', name: 'Zvěd', requires: ['kejklir', 'lovec'] },
  { id: 'vedmak', name: 'Vědmák', requires: ['mastickar', 'bojovnik'] },
  { id: 'alchymista', name: 'Alchymista', requires: ['mastickar', 'zarikavac'] },
  { id: 'carodej', name: 'Čaroděj', requires: ['zarikavac', 'bojovnik'] },
  { id: 'mag', name: 'Mág', requires: ['zarikavac', 'kejklir'] },
];

export const MASTER_PROFESSIONS = [
  { id: 'cernokneznik', name: 'Černokněžník', requires: ['saman', 'alchymista', 'mag'], theme: 'temná magie, mrtví, běsi, nekromantie' },
  { id: 'divotvurce', name: 'Divotvůrce', requires: ['saman', 'druid', 'alchymista', 'carodej'], theme: 'zázraky, proměny světa, tvořivá magie' },
  { id: 'inkvizitor', name: 'Inkvizitor', requires: ['zved', 'vedmak', 'mag'], theme: 'vyšetřování, odhalování, boj proti hrozbám' },
  { id: 'mstitel', name: 'Mstitel', requires: ['valecnik', 'hranicar', 'lupic', 'zved'], theme: 'pomsta, pronásledování, osobní válka' },
  { id: 'nicitel', name: 'Ničitel', requires: ['valecnik', 'hranicar', 'vedmak'], theme: 'drtivá síla, boj s monstry, destrukce' },
  { id: 'paladin', name: 'Paladin', requires: ['valecnik', 'vedmak', 'carodej'], theme: 'víra, ochrana, svatý boj, řád' },
  { id: 'stin', name: 'Stín', requires: ['lupic', 'alchymista', 'mag'], theme: 'utajení, vraždy, iluze, jedy' },
  { id: 'vudce', name: 'Vůdce', requires: ['valecnik', 'lupic', 'zved'], theme: 'velení, organizace, moc, vliv' },
  { id: 'zivlomag', name: 'Živlomág', requires: ['druid', 'carodej'], theme: 'živly, přírodní a ničivá magie' },
  { id: 'zrec', name: 'Žrec', requires: ['hranicar', 'saman', 'druid'], theme: 'kult, kmen, duchové, posvátná tradice' },
];
