import type { Theme } from '@/themes/types';

export const zlatyStandardTheme: Theme = {
  id: 'zlaty-standard',
  name: 'Zlatý standard',
  scope: 'both',
  atmosphere: 'Královský luxus — pure black + rich gold, no blue',
  vars: {
    '--bg-primary':       '#050508',
    '--bg-secondary':     '#0a0a0f',
    '--bg-card':          '#0c0c12',
    '--bg-card-hover':    '#121220',
    '--accent':           '#d4a017',
    '--accent-bright':    '#f0c040',
    '--accent-dim':       '#8a6510',
    '--accent-soft':      'rgba(212, 160, 23, 0.18)',
    '--text-primary':     '#f0e8d0',
    '--text-secondary':   '#907840',
    '--text-muted':       '#504030',
    '--border':           '#1a1510',
    '--border-subtle':    '#0a0808',
    '--border-strong':    '#d4a017',
    '--success':          '#3ecf8e',
    '--warning':          '#d4a017',
    '--danger':           '#c04040',
    '--info':             '#d4a017',
    '--text-on-accent':       '#050508',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(0, 0, 0, 0.8)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(212, 160, 23, 0.16)',
    '--warning-soft-border':  'rgba(212, 160, 23, 0.4)',
    '--danger-soft':          'rgba(192, 64, 64, 0.14)',
    '--danger-soft-border':   'rgba(192, 64, 64, 0.4)',
    '--danger-focus-ring':    'rgba(192, 64, 64, 0.3)',
    '--font-logo':        '"Cinzel Decorative", "Cinzel", Georgia, serif',
    '--font-display':     '"Cinzel", "Playfair Display", Georgia, serif',
    '--font-body':        '"Lato", "Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel Decorative',
    display: 'Cinzel',
    body: 'Lato',
  },
  thumbnail: '/themes/thumbnails/zlaty-standard.webp',
  background: '/themes/backgrounds/zlaty-standard.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
