import type { Theme } from '../../types';

export const hospodaTheme: Theme = {
  id: 'hospoda',
  name: 'Hospoda',
  scope: 'both',
  atmosphere: 'Středověká krčma — dřevo, pergamen, cechovní banner',
  vars: {
    '--bg-primary':       '#e8d4a0',
    '--bg-secondary':     '#d8c088',
    '--bg-card':          '#f0e0b0',
    '--bg-card-hover':    '#f8e8b8',
    '--accent':           '#8a1520',
    '--accent-bright':    '#b01828',
    '--accent-dim':       '#600810',
    '--accent-soft':      'rgba(138, 21, 32, 0.18)',
    '--text-primary':     '#2a1808',
    '--text-secondary':   '#604030',
    '--text-muted':       '#604020',
    '--border':           '#3a1e08',
    '--border-subtle':    '#2a1808',
    '--border-strong':    '#c8800a',
    '--success':          '#3a8a4e',
    '--warning':          '#c8800a',
    '--danger':           '#8a1520',
    '--info':             '#3060a0',
    '--text-on-accent':       '#f0e0b0',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(20, 10, 4, 0.7)',
    '--success-soft':         'rgba(58, 138, 78, 0.16)',
    '--success-soft-border':  'rgba(58, 138, 78, 0.4)',
    '--warning-soft':         'rgba(200, 128, 10, 0.16)',
    '--warning-soft-border':  'rgba(200, 128, 10, 0.4)',
    '--danger-soft':          'rgba(138, 21, 32, 0.16)',
    '--danger-soft-border':   'rgba(138, 21, 32, 0.4)',
    '--danger-focus-ring':    'rgba(138, 21, 32, 0.3)',
    '--font-logo':        '"Almendra", "MedievalSharp", Georgia, serif',
    '--font-display':     '"Lora", "Playfair Display", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Almendra',
    display: 'Lora',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/hospoda.webp',
  background: '/themes/backgrounds/hospoda.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
