import type { Theme } from '@/themes/types';

export const indianeTheme: Theme = {
  id: 'indiane',
  name: 'Indiánské',
  scope: 'both',
  atmosphere: 'Frontier západ — sunset, lapač snů, korálky, tyrkysová',
  vars: {
    '--bg-primary':       '#d4a870',
    '--bg-secondary':     '#c89860',
    '--bg-card':          '#e0bc88',
    '--bg-card-hover':    '#e8c898',
    '--accent':           '#97460c',
    '--accent-bright':    '#f08020',
    '--accent-dim':       '#803010',
    '--accent-soft':      'rgba(208, 96, 16, 0.18)',
    '--text-primary':     '#2a1808',
    '--text-secondary':   '#583b1d',
    '--text-muted':       '#503020',
    '--border':           '#805030',
    '--border-subtle':    '#3a1e08',
    '--border-strong':    '#c8900a',
    '--success':          '#3a8a4e',
    '--warning':          '#c8900a',
    '--danger':           '#a83838',
    '--info':             '#208080',
    '--text-on-accent':       '#ffffff',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(20, 10, 4, 0.7)',
    '--success-soft':         'rgba(58, 138, 78, 0.16)',
    '--success-soft-border':  'rgba(58, 138, 78, 0.4)',
    '--warning-soft':         'rgba(200, 144, 10, 0.16)',
    '--warning-soft-border':  'rgba(200, 144, 10, 0.4)',
    '--danger-soft':          'rgba(168, 56, 56, 0.16)',
    '--danger-soft-border':   'rgba(168, 56, 56, 0.4)',
    '--danger-focus-ring':    'rgba(168, 56, 56, 0.3)',
    '--font-logo':        '"Rye", "Playfair Display", Georgia, serif',
    '--font-display':     '"Lora", "IM Fell English", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Rye',
    display: 'Lora',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/indiane.webp',
  background: '/themes/backgrounds/indiane.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
