import type { Theme } from '@/themes/types';

export const magieTheme: Theme = {
  id: 'magie',
  name: 'Magie a kouzla',
  scope: 'both',
  atmosphere: 'Kouzelnická věž — fialová + zlato + krystaly',
  vars: {
    '--bg-primary':       '#060410',
    '--bg-secondary':     '#0c0618',
    '--bg-card':          '#100820',
    '--bg-card-hover':    '#160c2c',
    '--accent':           '#c8900a',
    '--accent-bright':    '#e8b020',
    '--accent-dim':       '#604808',
    '--accent-soft':      'rgba(200, 144, 10, 0.18)',
    '--text-primary':     '#e0d0f8',
    '--text-secondary':   '#8d6c9d',
    '--text-muted':       '#302040',
    '--border':           '#3a2050',
    '--border-subtle':    '#1c1030',
    '--border-strong':    '#8020d0',
    '--success':          '#3ecf8e',
    '--warning':          '#e8b020',
    '--danger':           '#c030a0',
    '--info':             '#20a8d0',
    '--text-on-accent':       '#06010c',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(4, 0, 12, 0.75)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(232, 176, 32, 0.14)',
    '--warning-soft-border':  'rgba(232, 176, 32, 0.4)',
    '--danger-soft':          'rgba(192, 48, 160, 0.14)',
    '--danger-soft-border':   'rgba(192, 48, 160, 0.4)',
    '--danger-focus-ring':    'rgba(192, 48, 160, 0.3)',
    '--font-logo':        '"Cinzel Decorative", "MedievalSharp", Georgia, serif',
    '--font-display':     '"Cinzel", "IM Fell English", Georgia, serif',
    '--font-body':        '"Lora", "EB Garamond", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel Decorative',
    display: 'Cinzel',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/magie.webp',
  background: '/themes/backgrounds/magie.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
