import type { Theme } from '@/themes/types';

export const ctyriZivlyTheme: Theme = {
  id: 'ctyri-zivly',
  name: 'Čtyři živly',
  scope: 'both',
  atmosphere: 'Elementální mandala — oheň, voda, země, vzduch + zlatá unifikace',
  vars: {
    '--bg-primary':       '#100c08',
    '--bg-secondary':     '#181208',
    '--bg-card':          '#1a1510',
    '--bg-card-hover':    '#221c14',
    '--accent':           '#c8900a',
    '--accent-bright':    '#e8b020',
    '--accent-dim':       '#604808',
    '--accent-soft':      'rgba(200, 144, 10, 0.16)',
    '--text-primary':     '#d8c090',
    '--text-secondary':   '#95754e',
    '--text-muted':       '#403020',
    '--border':           '#302818',
    '--border-subtle':    '#1c1810',
    '--border-strong':    '#c8900a',
    '--success':          '#6a8830',
    '--warning':          '#e86020',
    '--danger':           '#c04020',
    '--info':             '#2080d0',
    '--text-on-accent':       '#100c08',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(8, 6, 4, 0.7)',
    '--success-soft':         'rgba(106, 136, 48, 0.16)',
    '--success-soft-border':  'rgba(106, 136, 48, 0.4)',
    '--warning-soft':         'rgba(232, 96, 32, 0.14)',
    '--warning-soft-border':  'rgba(232, 96, 32, 0.4)',
    '--danger-soft':          'rgba(192, 64, 32, 0.14)',
    '--danger-soft-border':   'rgba(192, 64, 32, 0.4)',
    '--danger-focus-ring':    'rgba(192, 64, 32, 0.3)',
    '--fire-primary':         '#e86020',
    '--water-primary':        '#2080d0',
    '--earth-primary':        '#4a6020',
    '--air-primary':          '#c0d8e8',
    '--font-logo':        '"Cinzel Decorative", "Trajan Pro", Georgia, serif',
    '--font-display':     '"IM Fell English", "Cinzel", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel Decorative',
    display: 'IM Fell English',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/ctyri-zivly.webp',
  background: '/themes/backgrounds/ctyri-zivly.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
