import type { Theme } from '../../types';

export const nemrtviTheme: Theme = {
  id: 'nemrtvi',
  name: 'Nemrtví',
  scope: 'both',
  atmosphere: 'Gotická krypta — toxická zelená, kámen, lebky',
  vars: {
    '--bg-primary':       '#0a0c08',
    '--bg-secondary':     '#101410',
    '--bg-card':          '#141810',
    '--bg-card-hover':    '#1a2018',
    '--accent':           '#30c060',
    '--accent-bright':    '#50e080',
    '--accent-dim':       '#186030',
    '--accent-soft':      'rgba(48, 192, 96, 0.18)',
    '--text-primary':     '#c0b890',
    '--text-secondary':   '#6d7f5b',
    '--text-muted':       '#303828',
    '--border':           '#282e20',
    '--border-subtle':    '#181c14',
    '--border-strong':    '#30c060',
    '--success':          '#50e080',
    '--warning':          '#c8b888',
    '--danger':           '#8a1a10',
    '--info':             '#30c060',
    '--text-on-accent':       '#0a1808',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(0, 8, 0, 0.7)',
    '--success-soft':         'rgba(80, 224, 128, 0.14)',
    '--success-soft-border':  'rgba(80, 224, 128, 0.4)',
    '--warning-soft':         'rgba(200, 184, 136, 0.16)',
    '--warning-soft-border':  'rgba(200, 184, 136, 0.4)',
    '--danger-soft':          'rgba(138, 26, 16, 0.18)',
    '--danger-soft-border':   'rgba(138, 26, 16, 0.4)',
    '--danger-focus-ring':    'rgba(138, 26, 16, 0.3)',
    '--font-logo':        '"MedievalSharp", "UnifrakturMaguntia", Georgia, serif',
    '--font-display':     '"Cinzel", "IM Fell English", Georgia, serif',
    '--font-body':        '"Lora", "EB Garamond", Georgia, serif',
  },
  fonts: {
    logo: 'MedievalSharp',
    display: 'Cinzel',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/nemrtvi.webp',
  background: '/themes/backgrounds/nemrtvi.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
