import type { Theme } from '../../types';

export const bilaTheme: Theme = {
  id: 'bila',
  name: 'Bílá',
  scope: 'both',
  atmosphere: 'Krémová nebeská čistota — jediné světlé téma kolekce',
  vars: {
    '--bg-primary':       '#fbf6e9',
    '--bg-secondary':     '#f4ecd8',
    '--bg-card':          '#ffffff',
    '--bg-card-hover':    '#f8f1de',
    '--accent':           '#c4a057',
    '--accent-bright':    '#d4b878',
    '--accent-dim':       '#806530',
    '--accent-soft':      'rgba(196, 160, 87, 0.18)',
    '--text-primary':     '#3a2e1e',
    '--text-secondary':   '#7a6a4e',
    '--text-muted':       '#aa9a7e',
    '--border':           '#d8cca8',
    '--border-subtle':    '#e8dcb8',
    '--border-strong':    '#c4a057',
    '--success':          '#3a8a4e',
    '--warning':          '#c87820',
    '--danger':           '#a83838',
    '--info':             '#3060a0',
    '--font-logo':        '"Cinzel", Georgia, serif',
    '--font-display':     '"Cinzel", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel',
    display: 'Cinzel',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/bila.webp',
  background: '/themes/backgrounds/bila.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
