import type { Theme } from '../../types';

export const vesmirnaLodTheme: Theme = {
  id: 'vesmirna-lod',
  name: 'Vesmírná loď',
  scope: 'both',
  atmosphere: 'Vojenský hangár vesmírné lodi — cyan + amber, L-bracket HUD',
  vars: {
    '--bg-primary':       '#080b10',
    '--bg-secondary':     '#0c1018',
    '--bg-card':          '#101520',
    '--bg-card-hover':    '#151c28',
    '--accent':           '#00b8e8',
    '--accent-bright':    '#30d0ff',
    '--accent-dim':       '#005878',
    '--accent-soft':      'rgba(0, 184, 232, 0.15)',
    '--text-primary':     '#c8d8e8',
    '--text-secondary':   '#4d80ab',
    '--text-muted':       '#283848',
    '--border':           '#0f1820',
    '--border-subtle':    '#0a131a',
    '--border-strong':    '#00b8e8',
    '--success':          '#3ecf8e',
    '--warning':          '#e8a020',
    '--danger':           '#f06060',
    '--info':             '#00b8e8',
    '--text-on-accent':       '#04101a',
    '--text-on-danger':       '#050508',
    '--bg-overlay':           'rgba(0, 6, 12, 0.7)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(232, 160, 32, 0.12)',
    '--warning-soft-border':  'rgba(232, 160, 32, 0.4)',
    '--danger-soft':          'rgba(240, 96, 96, 0.12)',
    '--danger-soft-border':   'rgba(240, 96, 96, 0.4)',
    '--danger-focus-ring':    'rgba(240, 96, 96, 0.3)',
    '--font-logo':        '"Orbitron", "Russo One", sans-serif',
    '--font-display':     '"Rajdhani", "Exo 2", sans-serif',
    '--font-body':        '"Roboto Condensed", "Roboto", sans-serif',
  },
  fonts: {
    logo: 'Orbitron',
    display: 'Rajdhani',
    body: 'Roboto Condensed',
  },
  thumbnail: '/themes/thumbnails/vesmirna-lod.webp',
  background: '/themes/backgrounds/vesmirna-lod.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
