import type { Theme } from '../../types';

export const kyberpunkTheme: Theme = {
  id: 'kyberpunk',
  name: 'Kyberpunk',
  scope: 'both',
  atmosphere: 'Neonová megalopole v dešti — cyan + magenta',
  vars: {
    '--bg-primary':       '#050810',
    '--bg-secondary':     '#080c18',
    '--bg-card':          '#0a1020',
    '--bg-card-hover':    '#0f1830',
    '--accent':           '#00d8e8',
    '--accent-bright':    '#40f0ff',
    '--accent-dim':       '#006878',
    '--accent-soft':      'rgba(0, 216, 232, 0.15)',
    '--text-primary':     '#c8e8f8',
    '--text-secondary':   '#5090b0',
    '--text-muted':       '#203040',
    '--border':           '#0c1830',
    '--border-subtle':    '#080c18',
    '--border-strong':    '#e020c0',
    '--success':          '#3ecf8e',
    '--warning':          '#f5a623',
    '--danger':           '#e020c0',
    '--info':             '#00d8e8',
    '--text-on-accent':       '#04101a',
    '--text-on-danger':       '#050508',
    '--bg-overlay':           'rgba(0, 4, 12, 0.8)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(245, 166, 35, 0.12)',
    '--warning-soft-border':  'rgba(245, 166, 35, 0.4)',
    '--danger-soft':          'rgba(224, 32, 192, 0.16)',
    '--danger-soft-border':   'rgba(224, 32, 192, 0.4)',
    '--danger-focus-ring':    'rgba(224, 32, 192, 0.3)',
    '--font-logo':        '"Orbitron", "Exo 2", sans-serif',
    '--font-display':     '"Exo 2", "Rajdhani", sans-serif',
    '--font-body':        '"Roboto", "Inter", sans-serif',
  },
  fonts: {
    logo: 'Orbitron',
    display: 'Exo 2',
    body: 'Roboto',
  },
  thumbnail: '/themes/thumbnails/kyberpunk.webp',
  background: '/themes/backgrounds/kyberpunk.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
