import type { Theme } from '../../types';

export const temnaCervenTheme: Theme = {
  id: 'temna-cerven',
  name: 'Temná červeň',
  scope: 'both',
  atmosphere: 'Gotická katedrála upíří šlechty — krev a černá, nic jiného',
  vars: {
    '--bg-primary':       '#080404',
    '--bg-secondary':     '#100608',
    '--bg-card':          '#140808',
    '--bg-card-hover':    '#1c0c0c',
    '--accent':           '#8a0010',
    '--accent-bright':    '#c00018',
    '--accent-dim':       '#400008',
    '--accent-soft':      'rgba(138, 0, 16, 0.20)',
    '--text-primary':     '#d0a0a0',
    '--text-secondary':   '#704040',
    '--text-muted':       '#301818',
    '--border':           '#200808',
    '--border-subtle':    '#180404',
    '--border-strong':    '#8a0010',
    '--success':          '#3ecf8e',
    '--warning':          '#f5a623',
    '--danger':           '#e02030',
    '--info':             '#5ba4f5',
    '--font-logo':        '"MedievalSharp", "Cinzel", Georgia, serif',
    '--font-display':     '"IM Fell English", "Cinzel", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'MedievalSharp',
    display: 'IM Fell English',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/temna-cerven.webp',
  background: '/themes/backgrounds/temna-cerven.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
