import type { Theme } from '@/themes/types';

export const temnaCervenTheme: Theme = {
  id: 'temna-cerven',
  name: 'Temná červeň',
  scope: 'both',
  atmosphere: 'Gotická katedrála upíří šlechty — krev a černá, nic jiného',
  vars: {
    '--bg-primary':       '#080404',
    '--bg-secondary':     '#100608',
    '--bg-card':          '#140808',
    '--bg-card-hover':    '#1c0c0c',
    '--accent':           '#bd0016',
    '--accent-bright':    '#c00018',
    '--accent-dim':       '#400008',
    '--accent-soft':      'rgba(138, 0, 16, 0.20)',
    '--text-primary':     '#d0a0a0',
    '--text-secondary':   '#a76565',
    '--text-muted':       '#301818',
    '--border':           '#200808',
    '--border-subtle':    '#180404',
    '--border-strong':    '#8a0010',
    '--success':          '#3ecf8e',
    '--success-soft':     'rgba(62, 207, 142, 0.15)',
    '--success-soft-border': 'rgba(62, 207, 142, 0.30)',
    '--warning':          '#f5a623',
    '--warning-soft':     'rgba(245, 166, 35, 0.15)',
    '--warning-soft-border': 'rgba(245, 166, 35, 0.30)',
    '--danger':           '#e02030',
    '--danger-soft':      'rgba(224, 32, 48, 0.15)',
    '--danger-soft-border': 'rgba(224, 32, 48, 0.30)',
    '--danger-focus-ring': 'rgba(224, 32, 48, 0.20)',
    '--info':             '#5ba4f5',
    '--text-on-accent':   '#ffffff',
    '--text-on-danger':   '#ffffff',
    '--bg-overlay':       'rgba(0, 0, 0, 0.7)',
    '--font-logo':        '"MedievalSharp", "Cinzel", Georgia, serif',
    '--font-display':     '"IM Fell English", "Cinzel", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'MedievalSharp',
    display: 'IM Fell English',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/temna-cerven.webp',
  background: '/themes/backgrounds/temna-cerven.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
