import type { Theme } from '../../types';

export const pergamenTheme: Theme = {
  id: 'pergamen',
  name: 'Pergamen',
  scope: 'both',
  atmosphere: 'Starověká knihovna — pergamen, svíčky, inkoust',
  vars: {
    '--bg-primary':       '#1a0e06',
    '--bg-secondary':     '#241508',
    '--bg-card':          '#e8d8a8',
    '--bg-card-hover':    '#f0e0b8',
    '--accent':           '#8a1a10',
    '--accent-bright':    '#b02018',
    '--accent-dim':       '#601008',
    '--accent-soft':      'rgba(138, 26, 16, 0.18)',
    '--text-primary':     '#2a1a08',
    '--text-secondary':   '#5a3a18',
    '--text-muted':       '#806040',
    '--border':           '#4a2e10',
    '--border-subtle':    '#3a1e08',
    '--border-strong':    '#d08020',
    '--success':          '#3a8a4e',
    '--warning':          '#d08020',
    '--danger':           '#8a1a10',
    '--info':             '#3060a0',
    '--text-on-accent':       '#f0e0b8',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(20, 10, 4, 0.7)',
    '--success-soft':         'rgba(58, 138, 78, 0.16)',
    '--success-soft-border':  'rgba(58, 138, 78, 0.4)',
    '--warning-soft':         'rgba(208, 128, 32, 0.16)',
    '--warning-soft-border':  'rgba(208, 128, 32, 0.4)',
    '--danger-soft':          'rgba(138, 26, 16, 0.16)',
    '--danger-soft-border':   'rgba(138, 26, 16, 0.4)',
    '--danger-focus-ring':    'rgba(138, 26, 16, 0.3)',
    '--font-logo':        '"IM Fell English", "Libre Baskerville", Georgia, serif',
    '--font-display':     '"Lora", "Playfair Display", Georgia, serif',
    '--font-body':        '"Lora", "EB Garamond", Georgia, serif',
  },
  fonts: {
    logo: 'IM Fell English',
    display: 'Lora',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/pergamen.webp',
  background: '/themes/backgrounds/pergamen.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
