import type { Theme } from '../../types';

export const slunceTheme: Theme = {
  id: 'slunce',
  name: 'Slunce',
  scope: 'both',
  atmosphere: 'Spálená země pod sluncem — amber + černá, antické ruiny',
  vars: {
    '--bg-primary':       '#120c04',
    '--bg-secondary':     '#180e06',
    '--bg-card':          '#1e1408',
    '--bg-card-hover':    '#261a0c',
    '--accent':           '#c88010',
    '--accent-bright':    '#e8a020',
    '--accent-dim':       '#604008',
    '--accent-soft':      'rgba(200, 128, 16, 0.18)',
    '--text-primary':     '#e8c070',
    '--text-secondary':   '#806030',
    '--text-muted':       '#381e08',
    '--border':           '#2a1e0c',
    '--border-subtle':    '#180c04',
    '--border-strong':    '#c88010',
    '--success':          '#6a8830',
    '--warning':          '#d06010',
    '--danger':           '#a83838',
    '--info':             '#c88010',
    '--text-on-accent':       '#120c04',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(8, 4, 0, 0.75)',
    '--success-soft':         'rgba(106, 136, 48, 0.14)',
    '--success-soft-border':  'rgba(106, 136, 48, 0.4)',
    '--warning-soft':         'rgba(208, 96, 16, 0.16)',
    '--warning-soft-border':  'rgba(208, 96, 16, 0.4)',
    '--danger-soft':          'rgba(168, 56, 56, 0.16)',
    '--danger-soft-border':   'rgba(168, 56, 56, 0.4)',
    '--danger-focus-ring':    'rgba(168, 56, 56, 0.3)',
    '--font-logo':        '"Cinzel", "Trajan Pro", Georgia, serif',
    '--font-display':     '"Cinzel", "Playfair Display", Georgia, serif',
    '--font-body':        '"Lora", "EB Garamond", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel',
    display: 'Cinzel',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/slunce.webp',
  background: '/themes/backgrounds/slunce.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
