import type { Theme } from '../../types';

export const modreNebeTheme: Theme = {
  id: 'modre-nebe',
  name: 'Modré nebe',
  scope: 'both',
  atmosphere: 'Heroická fantasy říše pod hvězdnatým modrým nebem',
  vars: {
    '--bg-primary':       '#0a1428',
    '--bg-secondary':     '#101e3c',
    '--bg-card':          '#142850',
    '--bg-card-hover':    '#1c3464',
    '--accent':           '#c89a30',
    '--accent-bright':    '#e8b860',
    '--accent-dim':       '#604814',
    '--accent-soft':      'rgba(200, 154, 48, 0.15)',
    '--text-primary':     '#e8e0c8',
    '--text-secondary':   '#a89870',
    '--text-muted':       '#544830',
    '--border':           '#2a3858',
    '--border-subtle':    '#1c2840',
    '--border-strong':    '#c89a30',
    '--success':          '#3ecf8e',
    '--warning':          '#f5a623',
    '--danger':           '#f06060',
    '--info':             '#5ba4f5',
    '--font-logo':        '"Cinzel Decorative", "Cinzel", Georgia, serif',
    '--font-display':     '"Cinzel", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel Decorative',
    display: 'Cinzel',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/modre-nebe.webp',
  background: '/themes/backgrounds/modre-nebe.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
