import type { Theme } from '@/themes/types';

export const arabskySvetTheme: Theme = {
  id: 'arabsky-svet',
  name: 'Arabský svět',
  scope: 'both',
  atmosphere: 'Arabský palác — burgundy, tyrkysová, zlato, arabesque',
  vars: {
    '--bg-primary':       '#100608',
    '--bg-secondary':     '#1a0810',
    '--bg-card':          '#082028',
    '--bg-card-hover':    '#0c2830',
    '--accent':           '#c8900a',
    '--accent-bright':    '#e8b020',
    '--accent-dim':       '#604808',
    '--accent-soft':      'rgba(200, 144, 10, 0.18)',
    '--text-primary':     '#e8d0a0',
    '--text-secondary':   '#98724c',
    '--text-muted':       '#402820',
    '--border':           '#6a0820',
    '--border-subtle':    '#3a0410',
    '--border-strong':    '#c8900a',
    '--success':          '#208878',
    '--warning':          '#c8900a',
    '--danger':           '#a83838',
    '--info':             '#208878',
    '--text-on-accent':       '#100608',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(12, 4, 8, 0.75)',
    '--success-soft':         'rgba(32, 136, 120, 0.16)',
    '--success-soft-border':  'rgba(32, 136, 120, 0.4)',
    '--warning-soft':         'rgba(200, 144, 10, 0.16)',
    '--warning-soft-border':  'rgba(200, 144, 10, 0.4)',
    '--danger-soft':          'rgba(168, 56, 56, 0.16)',
    '--danger-soft-border':   'rgba(168, 56, 56, 0.4)',
    '--danger-focus-ring':    'rgba(168, 56, 56, 0.3)',
    '--font-logo':        '"Cinzel Decorative", "Scheherazade", Georgia, serif',
    '--font-display':     '"Lora", "Playfair Display", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel Decorative',
    display: 'Lora',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/arabsky-svet.webp',
  background: '/themes/backgrounds/arabsky-svet.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
