import type { Theme } from '@/themes/types';

export const mesicTheme: Theme = {
  id: 'mesic',
  name: 'Měsíc',
  scope: 'both',
  atmosphere: 'Měsíční pohádkové království — stříbrná + glassmorphism',
  vars: {
    '--bg-primary':       '#06091a',
    '--bg-secondary':     '#0a1028',
    '--bg-card':          '#0e163a',
    '--bg-card-hover':    '#121e48',
    '--accent':           '#6090e0',
    '--accent-bright':    '#80b0ff',
    '--accent-dim':       '#203060',
    '--accent-soft':      'rgba(96, 144, 224, 0.18)',
    '--text-primary':     '#e8f0ff',
    '--text-secondary':   '#6880b0',
    '--text-muted':       '#1e2a48',
    '--border':           '#405880',
    '--border-subtle':    '#202c3c',
    '--border-strong':    '#b8cce8',
    '--success':          '#3ecf8e',
    '--warning':          '#d4b878',
    '--danger':           '#e08080',
    '--info':             '#6090e0',
    '--text-on-accent':       '#04081a',
    '--text-on-danger':       '#050508',
    '--bg-overlay':           'rgba(0, 4, 16, 0.65)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(212, 184, 120, 0.14)',
    '--warning-soft-border':  'rgba(212, 184, 120, 0.4)',
    '--danger-soft':          'rgba(224, 128, 128, 0.14)',
    '--danger-soft-border':   'rgba(224, 128, 128, 0.4)',
    '--danger-focus-ring':    'rgba(224, 128, 128, 0.3)',
    '--font-logo':        '"Great Vibes", "Tangerine", "Cinzel", Georgia, serif',
    '--font-display':     '"Cinzel", "Playfair Display", Georgia, serif',
    '--font-body':        '"Lora", "EB Garamond", Georgia, serif',
  },
  fonts: {
    logo: 'Great Vibes',
    display: 'Cinzel',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/mesic.webp',
  background: '/themes/backgrounds/mesic.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
