const FANTASY_DESCRIPTIONS: Record<string, string> = {
  '1': `Pohádkový les je jasný, živý a neobyčejně uklidňující prostor, ve kterém téměř nevzniká pocit ohrožení. Převládají zde vysoké stále zelené stromy, jejichž koruny vytvářejí měkký zelený strop, skrz který pronikají paprsky světla v jemných pruzích. Zem je pokrytá hebkým mechem, nízkými kapradinami, borůvčím a místy drobnými květy, které mezi zelení působí téměř slavnostně.

Vzduch tu voní jehličím, vlhkou hlínou a čistotou, jakou mívají lesy, do nichž lidská ruka zasahovala jen málo. Mezi stromy se běžně objevují jeleni, srnky, lišky, zajíci, veverky i drobní pěvci, kteří se chovají klidněji než jinde a nepůsobí plaše. Les není temný ani tísnivý, naopak působí dojmem místa, které člověka přijímá a tiše chrání. Potůčky jsou průzračné, kameny hladké, světlo měkké a i hlubší části lesa si uchovávají zvláštní pocit bezpečí, jako by zde příroda byla v dokonalé rovnováze.`,

  '2': `Rozvaliny horské strážnice leží vysoko na skalnatém výběžku, kde se krajina láme do prudkých svahů a kamenitých stezek. Z někdejší stavby zůstaly silné obvodové zdi, část strážní věže, zbytky nádvoří a sesuté kamenné bloky, mezi nimiž roste horská tráva, mech a nízké keře. Kámen je vyšisovaný větrem, deštěm a zimou, místy popraskaný a tmavší od vlhkosti, jinde světlý a ostrý jako kostra dávno mrtvého obra.

Okolí je otevřené, s dalekým výhledem na průsmyky, lesy a cesty v údolí. Vítr tu téměř nikdy úplně neutichá a prohání se prázdnými okenními otvory i rozpadlými schodišti, takže ruina působí stroze, chladně a nehostinně. V některých částech jsou stále patrné zbytky střílen, kusy vnitřních zdí a propadlé vstupy do spodních prostor. Celé místo vyvolává dojem dávné kázně a vojenského pořádku, který rozdrtila léta, počasí a opuštěnost.`,

  '3': `Zatopený chrám vyrůstá z klidné nebo pomalu proudící vody jako pozůstatek dávné víry, kterou krajina postupně pohltila. Nad hladinou jsou vidět kamenné schody, části sloupoví, porušené oblouky a vrchní část hlavní svatyně, zatímco zbytek stavby mizí pod zelenavou či tmavou vodou. Kámen je porostlý řasami, mechem a vlhkými popínavými rostlinami, které chrámu dodávají zvláštní krásu i pocit zapomenutosti.

Na některých místech voda sahá jen po kolena, jinde se náhle propadá do hlubších částí, v nichž pod hladinou tušíš dlažbu, sochy nebo boční chodby. Sloupy jsou popraskané, reliéfy obroušené časem a některé postavy bohů či světců mají odpadlé tváře nebo ruce, jako by je pomalu požírala sama voda. V tichu je slyšet jen šplouchání, kapání a občasný pohyb ptáků nebo hmyzu nad hladinou. Místo působí posvátně, krásně a zároveň smutně, jako připomínka něčeho velkého, co se propadlo do mlčení.`,

  '4': `Hostinec U Poslední lucerny stojí stranou hlavního ruchu, u cesty, která už nepůsobí tak bezpečně a udržovaně jako v blízkosti měst. Budova je bytelná, starší, postavená ze dřeva a kamene, se širokou střechou, oprýskaným štítem a zavěšenou lucernou, která bývá po večerech skutečně posledním světlem široko daleko. Okna vyzařují teplé žluté světlo, z komína stoupá kouř a ve dveřích je cítit směs pečeného masa, piva, dřeva a vlhka z cestovních plášťů.

Uvnitř je prostor tmavší, ale útulný, s těžkými trámy, poškrábanými stoly, lavicemi, barelem v rohu a krbem, kolem něhož se drží nejvíce lidí. Na stěnách visí lovecké trofeje, staré mapy, zrezivělé zbraně a drobnosti, které tu zanechali cestovatelé nebo které hostinský za léta nasbíral. Hostinec nepůsobí honosně, ale pevně a zabydleně, jako místo, které pamatuje stovky příběhů, hádek, noclehů i tajemství. Když se setmí, celé místo získává měkkou, téměř zlatavou atmosféru bezpečí uprostřed nejistého světa za dveřmi.`,

  '5': `Mlžné hřbitovní návrší se zvedá mírně nad okolní krajinu a už z dálky působí odděleně od běžného života. Staré kamenné náhrobky stojí nakřivo, některé jsou zarostlé mechem, jiné prasklé nebo napůl propadlé do země, jako by je čas pomalu vtahoval dolů. Mezi hroby rostou tmavé cypřiše, zkroucené tisy nebo staré listnaté stromy s holými větvemi, které dávají místu stísněný a nehybný ráz.

Mlha se zde drží neobyčejně často a nízko, plazí se mezi kameny, obepíná základy malé hřbitovní kaple a tlumí obrysy všeho, co stojí dál než pár kroků. Kaple sama je omšelá, s oprýskanými dveřmi, vlhkými zdmi a malým zvonem, který už dávno nezní tak, jak by měl. Půda bývá měkká, vzduch studenější než v okolí a ticho těžší, přerušované jen větrem nebo vzdáleným krákáním havranů. Celé místo nepůsobí násilně ani přehnaně strašidelně, spíš starobně, smutně a neklidně, jako prostor, kde se vzpomínky drží déle než lidé.`,

  '6': `Starý stříbrný důl je zasazený do úbočí kopce nebo hory, v krajině, která kolem sebe nese stopy někdejší lidské práce, ale dnes už působí opuštěně a zarostle. U vstupu se ještě mohou válet zbytky trámů, rozbité vozíky, rezavé nástroje, propadlé přístřešky a hromady vytěženého kamene, mezi nimiž prorůstá tráva, mech a houževnaté křoviny. Samotný vstup do dolu bývá tmavý, chladný a podepřený starými výztužemi, které na některých místech stále drží, jinde jsou nahnuté nebo napůl sesuté.

Uvnitř panuje stálý chlad, vlhkost a těžký vzduch, v němž je cítit mokrý kámen, hlína a kov. Stěny nesou stopy nástrojů, místy se v nich ještě zachycují slabé odlesky rudných žil nebo lesk minerálů, které ve světle pochodně či lampy působí téměř krásně. Voda tu odkapává ze stropů, stéká po stěnách a v některých nižších částech se shromažďuje do kaluží nebo úzkých podzemních tůní. Celé místo má zvláštní směs syrovosti, ticha a dávné pracovitosti, jako by lidé odešli jen proto, že už dál nemohli, ne proto, že by sami chtěli.`,

  '7': `Kamenný kruh stojí uprostřed otevřené krajiny, kde široké nebe a prázdný prostor zdůrazňují jeho osamělost i význam. Tvoří jej několik mohutných kamenů vztyčených do kruhu, některé jsou vysoké jako menší dům, jiné nižší a masivnější, všechny však působí starobně, neotřesitelně a cize vůči okolní krajině. Jejich povrch je obroušený větrem a deštěm, porostlý lišejníkem, mechem a místy jemně popraskaný, přesto stále pevný a nečekaně majestátní.

Půda uvnitř kruhu bývá odlišná od okolí, tvrdší, sušší, nebo naopak měkčí a tmavší, jako by se tam po staletí odehrávalo něco, co krajinu poznamenalo. Když fouká vítr, obtéká kameny zvláštním způsobem a vydává hlubší, táhlejší zvuk než v otevřeném poli kolem. Celé místo je prosté a téměř prázdné, a právě tím působí silněji než okázalé stavby. Není na něm nic přebytečného, jen kámen, zem, nebe a pocit, že tento kruh stál na svém místě dávno před tím, než si lidé začali pamatovat vlastní dějiny.`,

  '8': `Lesní lovecký zámeček je ukrytý mezi vysokými stromy, ale sám o sobě nepůsobí opuštěně ani zanedbaně; naopak z něj vyzařuje udržovaná elegance a stará šlechtická tradice. Stavba bývá rozložitá, s dřevěnými i kamennými prvky, honosnější než běžný venkovský dům, ale méně okázalá než městský palác. Kolem se rozprostírají upravené cesty, stáje, menší hospodářské budovy, dvůr a části lesa, které byly přizpůsobeny lovu i pohodlnému pohybu hostů.

Uvnitř bývá cítit dřevo, vosk, víno, kůže a kouř z krbů. Stěny zdobí trofeje jelenů, divočáků, vycpaní ptáci, lovecké obrazy, erbovní štíty a těžké závěsy, které tlumí zvuk a dodávají místnostem měkký, teplý ráz. Salony a jídelny působí reprezentativně, ale ne strojeně; je zřejmé, že zde šlechtici nejen odpočívají, ale také jednají, sledují se navzájem a vedou rozhovory, které nejsou určeny pro cizí uši. Zámeček tak spojuje krásu okolní přírody s přepychem a neviditelným napětím společnosti, která si zvykla usmívat se i tehdy, když ve skutečnosti vede tichý boj.`,

  '9': `Malá víska leží stranou hlavních tahů, mimo ruch měst, karavan i častých návštěv. Domy jsou nízké, prosté a stavěné z místního dřeva, kamene nebo hlíny, střechy bývají doškové nebo šindelové a celé místo působí dojmem, že si vystačí samo se sebou. Cesty mezi domy nejsou široké ani dokonale upravené, spíš vyšlapané a přirozeně vzniklé, lemované ploty, dřevníky, studnami a malými zahradami.

Ve vzduchu je cítit dřevo, kouř, hlína, seno a někdy i chléb nebo polévka vařící se v domácnostech. Lidé zde žijí pomalejším rytmem, vázaným na roční období, práci a vlastní zvyky, které se předávají spíše mlčky než vysvětlováním. Vesnice působí klidně, ale i uzavřeně; všechno je zde menší, bližší a osobnější než ve městě. Na návsi může stát malá kaplička, starý strom nebo lavice, u nichž se schází místní, a za posledními domy už rychle začínají pole, louky nebo les, jako by civilizace končila hned za prahem.`,

  '10': `Jeskyně pod vodopádem je skrytá za širokým pásem padající vody, který zvenčí zakrývá vstup tak dokonale, že si ho člověk bez předchozí znalosti téměř nevšimne. Samotný vodopád vytváří neustálý hukot, jemnou vodní tříšť a chladný, čistý vzduch, v němž se světlo láme do lesklých odrazů na mokrých kamenech. Už přístup k jeskyni působí zvláštně, protože člověk musí projít skrz padající vodu nebo úzkou stezkou těsně při skále, než se před ním otevře tmavý prostor ukrytý za tekoucí stěnou.

Uvnitř je chladno, vlhko a ozvěna každého kroku se mísí s tlumeným duněním vody za stěnou. Strop i stěny se lesknou mokrem, z kamene visí drobné krápníky nebo tenké závoje minerálních usazenin a v mělkých tůních se odráží slabé světlo pronikající zvenčí. Vnitřní prostor může být překvapivě široký, s několika výklenky, kamennými plošinami a hlubšími chodbami, které mizí ve tmě. Jeskyně tak působí zároveň skrytě i vznešeně, jako přírodní síň vytvořená vodou, kamenem a časem.`,

  '11': `Pobřeží řeky je klidné, otevřené a působí jako místo, kde čas plyne pomaleji než jinde. Břeh bývá tvořen směsí jemné trávy, hlinité půdy, oblázků a místy nízkých kořenů stromů, které se sklánějí nad vodu a vytvářejí příjemný stín. Řeka zde neteče divoce ani nebezpečně, spíše široce a vyrovnaně, s hladinou, která se leskne podle světla a jen občas ji rozruší kruhy po rybě nebo slabší proud kolem kamenů.

V okolí rostou vrby, olše nebo rákosí, které se ve větru lehce pohupují a doplňují zvuk tekoucí vody o měkké šustění. Vzduch je vlhký, čistý a nese s sebou vůni vody, bahna, trávy a někdy i rybiny. Místo nepůsobí nijak divoce ani opuštěně, spíš přirozeně a pokojně, jako část krajiny, kam lidé chodí odpočívat, posedět v tichu nebo prostě jen sledovat proud. Je to krajinný obraz prosté krásy, bez okázalosti, ale s velmi silným pocitem klidu a stability.`,

  '12': `Přístav je neustále živý, hlučný a plný pohybu, i když se jeho tvář mění podle hodiny, počasí a typu lodí, které právě kotví u mola. Dřevěná mola, kamenné nábřeží, sklady, jeřáby, provazy, sudy a sítě vytvářejí prostor, který je zároveň pracovním místem i tepajícím centrem města nebo pobřežní osady. Všude je slyšet křik námořníků, rány beden, volání obchodníků, skřípání lan a zvuk vody narážející do boků lodí.

Ve vzduchu se mísí sůl, rybina, kouř, dehet, mokré dřevo a pach lidí, kteří žijí z moře nebo na moři. Lodě samotné dodávají přístavu charakter; některé jsou obchodní a těžkopádné, jiné štíhlé, rychlé a podezřelé, další nesou znaky vojska, moci nebo bohatství. Mezi běžnými dělníky a námořníky se tu pohybují vojáci, pobudové, pašeráci, ženy z přístavních čtvrtí, poslové i cizinci, kteří připluli z míst, o nichž místní nikdy neslyšeli. Přístav tak nepůsobí jen jako pobřeží s loděmi, ale jako živý organismus plný příběhů, špíny, napětí a neustálé změny.`,

  '13': `Poutnická kaple stojí na místě, kde se stýkají staré cesty, a už na první pohled působí prostě, skromně a tiše. Je to menší kamenná nebo dřevěná stavba se šindelovou střechou, jednoduchou věžičkou či zvonicí a malými okny, která dovnitř propouštějí měkké světlo. Kolem kaple bývá několik stromů, studna, kamenný kříž, lavička nebo malé ohniště, kde si poutníci mohou odpočinout, než se znovu vydají na cestu.

Samotné místo nepůsobí bohatě ani slavnostně, ale nese v sobě zvláštní důstojnost. Uvnitř bývá chladněji, voní to voskem, starým dřevem, modlitbou a prachem, který se usazuje na lavicích, obrazech a drobných obětních darech. Na zdech mohou viset jednoduché malby svatých, dřevěné symboly, děkovné stužky nebo předměty zanechané lidmi, kteří zde prosili o ochranu. Celé rozcestí s kaplí působí jako tichý bod mezi jednotlivými světy, místo na krátké zastavení, nadechnutí a vyrovnání mysli.`,

  '14': `Tichý klášter je ukrytý hluboko mezi stromy, stranou od běžných cest a lidského ruchu, takže působí téměř jako součást lesa samotného. Je tvořen uzavřeným souborem kamenných budov s vnitřním dvorem, arkádami, zahradou, kaplí, hospodářskými částmi a někdy i menší knihovnou nebo bylinkářskou zahradou. Zdi jsou staré, pevné a místy porostlé břečťanem, střechy tmavé a těžké, okna úzká a celkový vzhled kláštera zdůrazňuje řád, jednoduchost a zdrženlivost.

Uvnitř i kolem něj panuje neobvyklé ticho, které nepůsobí prázdně, ale soustředěně. Je slyšet kroky na kameni, vzdálený zvon, šum listí, vítr v korunách a občas tlumené hlasy lidí, kteří si zvykli mluvit málo a tiše. V zahradách rostou léčivé byliny, zelenina, ovocné stromy nebo vinná réva, zatímco uvnitř budov se drží chlad kamene, vůně starých knih, vosku, pryskyřice a sušených rostlin. Klášter působí jako místo oddělené od běžného světa, ne nepřátelské, ale zdrženlivé a uzavřené do vlastního rytmu.`,

  '15': `Horský průsmyk je dlouhý, úzký tah mezi skalami a horskými svahy, kde krajina působí tvrdě, otevřeně a neúprosně. Cesta se vine mezi kameny, sutí, útesy a ostrými svahy, někde je dost široká pro povozy, jinde se stahuje do úzkých míst, kde vedle sebe sotva projdou dva jezdci. Nad hlavou se zvedají skály, místy holé a šedé, jinde porostlé nízkými borovicemi, klečí nebo horskou trávou, která se drží v puklinách navzdory větru a chladu.

Vzduch je zde ostřejší než dole v údolí a často se mění; jednou je průzračný a jasný, jindy se sem valí mlha, déšť nebo prach z cesty. Zvuky se v průsmyku nesou zvláštně daleko, takže kroky, hlasy, cinknutí výstroje nebo dusot kopyt získávají větší váhu než v otevřené krajině. Místo samo o sobě nepůsobí mrtvě, ale přísně a soustředěně, jako krajina, která člověka nutí neustále vnímat její pravidla.`,

  '16': `Vlčí hrádek stojí na vyvýšeném místě při hranici nebo na okraji neklidného kraje, kde jeho silueta působí tvrdě, stroze a účelně. Není stavěný pro krásu ani okázalost, ale pro obranu, dohled a přežití, a tomu odpovídá každý kámen, dřevěná palisáda i rozvržení nádvoří. Hlavní věž bývá masivní a hranatá, obvodové zdi silné, brána těžká a okolí zbavené všeho, co by mohlo nepříteli poskytnout kryt.

Uvnitř hrádku je vše podřízeno vojenskému řádu. Na nádvoří se pohybují vojáci, koně, sluhové a zbrojíři, na zdech hlídky, ve stájích a skladištích panuje účelný nepořádek a ve vzduchu je cítit kouř, pot, kůže, kov a mokrý kámen. Obytné prostory nejsou pohodlné, spíš strohé a opotřebované každodenním používáním, s jednoduchými lavicemi, hrubými stoly, mapami, zbraněmi a těžkými přikrývkami. Celé místo působí neústupně, jako sevřená pěst zasazená do krajiny, která má vydržet nepohodlí, útok i dlouhou zimu.`,

  '17': `Tržiště je otevřený, hlučný a barevný prostor, v němž se od rána do večera mísí pohyb, hlasy, vůně a neustálé drobné střety lidských zájmů. Stánky, plachty, vozy, sudy, koše a provizorní pulty zaplňují náměstí nebo širokou ulici tak hustě, že mezi nimi člověk téměř neustále kličkuje. Každý kout má jinou barvu a rytmus; někde se prodává ovoce, jinde látky, nářadí, keramika, koření, kožešiny nebo pečivo, a každý prodejce se snaží přehlušit ostatní.

Vzduch je plný hlasů, smíchu, smlouvání, volání a útržků cizích rozhovorů, které se ztrácejí stejně rychle, jako vznikají. Vůně jídla, koní, prachu, potu, kouře a koření vytváří směs, která je chaotická, ale živá a lidská. Mezi prostými venkovany a zákazníky se pohybují řemeslníci, obchodníci, děti, kapsáři, žebráci i lidé, kteří sem přišli hlavně proto, aby slyšeli novinky a viděli ostatní. Tržiště nepůsobí jako jedno místo, ale jako desítky malých světů namačkaných vedle sebe, spojených hlukem, zvědavostí a neustálým proudem života.`,

  '18': `Starý maják stojí osaměle na pobřeží, na skále nebo výběžku nad mořem, kde je vystaven větru, soli a nekonečnému pohledu do dálky. Jeho věž je vysoká, štíhlá nebo lehce rozšířená při základně, postavená z kamene, který byl léty ohlazený a místy popraskaný, zatímco kovové části dávno ztratily původní lesk. Okolní budovy, pokud tam ještě jsou, bývají nízké, zanedbané a poloprázdné, s rozbitými okenicemi, vyvrácenými dveřmi nebo střechami, které už jen zčásti odolávají počasí.

Uvnitř majáku vede vzhůru úzké točité schodiště, po němž se stoupá kolem chladných zdí, starých výklenků, zbytků nářadí a prachu navátého větrem. V nejvyšší části bývalo světlo, ale dnes tam zůstává jen prázdný prostor, zrezivělý mechanismus, skla matná od soli a výhled na moře, které působí nekonečně a lhostejně. Všude je slyšet vítr, vzdálené vlny a občasné skřípění konstrukce, které dává stavbě téměř živý, ale unavený hlas.`,

  '19': `Dřevorubecká mýtina je otevřený prostor vysekaný z lesa, kde je na první pohled patrné, že příroda zde ustoupila lidské práci jen dočasně a neochotně. Zem bývá rozježděná povozy, rozrytá botami a posetá pilinami, štěpinami, větvemi a kusy kmenů, které čekají na další zpracování nebo odvoz. Po obvodu stojí sruby, přístřešky, hranice dřeva, pracovní stoly, jednoduché sklady a někdy i ohniště nebo přístřešek pro koně.

Vzduch je plný vůně čerstvě poraženého dřeva, smůly, kouře a vlhké lesní půdy. Ozývá se tu rytmické sekání, praskání kmenů, hlasité volání mužů při práci i chvíle náhlého ticha, kdy se celý les kolem zdá poslouchat. Mýtina nepůsobí uhlazeně ani příjemně v měkkém smyslu, ale je v ní poctivá, syrová energie každodenní námahy. Je to místo střetu lesa a člověka, kde civilizace ještě nezvítězila, jen si na okamžik vybojovala prostor mezi stromy.`,

  '20': `Zbořený most se klene nad řekou už jen ve zbytcích, které dávají tušit, jak důležitý a pevný kdysi býval. Zůstaly po něm kamenné pilíře, části oblouků, ulámané kraje vozovky a trosky trámů nebo zdiva, které leží v proudu i podél břehů. Některé části mostu jsou zarostlé travou, mechem a křovinami, jiné jsou hladce obroušené vodou a časem, takže celé místo působí zároveň zničeně i zvláštně krásně.

Řeka pod mostem může být klidná nebo silnější, ale vždy dodává troskám pohyb a zvuk, který zvýrazňuje jejich nehybnost. Voda naráží do kamenů, obtéká spadlé části konstrukce a vytváří víry, pěnu i temnější hlubší místa mezi pilíři. Na jednom nebo obou březích zůstávají zbytky staré cesty, která k mostu vedla, ale teď se najednou ztrácí do prázdna. Celé místo působí jako přerušená věta v krajině, jako památka na spojení, které kdysi existovalo, ale bylo násilně nebo nevyhnutelně ukončeno.`,
};

export default FANTASY_DESCRIPTIONS;
