const MYSTIC_DESCRIPTIONS: Record<string, string> = {
  '1': `Temný hrad stojí nad městem nebo menší obcí jako pozůstatek jiné doby, který už dávno ztratil svůj původní význam, ale ne svou přítomnost. Ve dne sem chodí turisté, školní výpravy a občas i páry, které se chtějí projít po nádvoří a podívat se z věže do kraje, takže místo působí jako běžná historická památka. Jakmile se ale setmí a brána se zavře, celý hrad se změní; jeho zdi působí vyšší, prázdné sály chladnější a ticho mezi kameny začne mít nepříjemnou váhu.

Chodby jsou úzké, omítka oprýskaná, na schodech se drží vlhkost a staré dřevo dveří i trámů nese stopy stáří, které už nepůsobí romanticky, ale unaveně a neklidně. Ve vnitřních nádvořích vane vítr jinak než dole ve městě a z temných okenních otvorů je někdy vidět světlo, které tam podle správy objektu vůbec nemá být. V některých částech hradu zůstaly zazděné místnosti, staré depozitáře, kaple bez vybavení nebo části sklepení, které nejsou přístupné veřejnosti a o nichž se oficiálně téměř nemluví. Hrad tak nepůsobí jako kulisa k historii, ale jako místo, které si kus minulosti nechalo pro sebe a nechce ho úplně vydat.`,

  '2': `Přes den jde o obyčejné centrum města, plné lidí, kaváren, tramvají, světel výloh a spěchu, ale po půlnoci se stejné ulice promění v něco podivně cizího. Hlavní tahy zůstávají osvětlené, ale boční uličky se propadají do ticha, v němž zní každý krok příliš hlasitě a každé odražené světlo vypadá na mokré dlažbě jinak, než by mělo. Fasády domů jsou najednou vyšší, průchody delší, v oknech se objevují odrazy, které neodpovídají tomu, co stojí proti nim, a známé město začne působit jako labyrint.

Vzduch bývá chladnější než přes den, nese pach deště, kamene, odpadků, kouře a něčeho neurčitě starého, co se mezi domy drží i přes moderní reklamy a provoz. Některé pasáže jsou zavřené řetězy, jiné vedou do vnitrobloků, kde se náhle ztratí hluk města, a člověk má pocit, že vstoupil do mezery mezi běžnou realitou a něčím, co se otevírá jen v určitou hodinu. Téměř nikdo tu není, jen občas osamělý člověk, vzdálený smích, zvuk lahve kutálející se po zemi nebo silueta, která zmizí dřív, než se dá pořádně rozeznat.`,

  '3': `Stará hospoda stojí trochu stranou hlavního ruchu, možná na okraji města, možná v zapadlé části vesnice, a na první pohled vypadá jen jako místo, které přežilo svou dobu. Vývěsní štít je oprýskaný, okna lehce zažloutlá od letitého kouře a světla, omítka místy popraskaná a dveře těžké od tisíců doteků. Uvnitř je přítmí, staré dřevěné stoly, výčep pamatující několik generací, zrcadlo za barem, které už nevrací úplně čistý obraz, a vzduch plný piva, dřeva, mastnoty, vlhkých kabátů a dávno zažraných rozhovorů.

Do hospody chodí stále podobní lidé, kteří mají svá místa, své zvyky a své ticho. Na zdech visí staré fotografie, výstřižky z novin, myslivecké trofeje nebo místní památky, ale některé tváře na snímcích už nikdo neumí přesně zařadit a některé příběhy se vyprávějí pokaždé trochu jinak. Hospoda tak není jen podnik, ale živá paměť kraje, místo, kde se minulost nerozpadla, jen se usadila v rozích, ve skle a v hlasech, které po zavírací době jako by úplně neutichaly.`,

  '4': `Muzeum bývá přes den přehledné, tiché a uhlazené, prostor plný vitrín, popisků, zabezpečení a návštěvníků, kteří pomalu procházejí mezi exponáty a dívají se na minulost jako na něco bezpečně uzavřeného za sklem. Budova sama ale často bývá starší než její současné využití; může jít o bývalý šlechtický palác, městský dům, klášter nebo instituci, jejíž zdi pamatují víc než jen výstavní provoz. Jakmile se zavřou dveře, zhasne část světel a v chodbách zůstane jen noční režim, začne prostor působit mnohem méně neutrálně.

Každý sál má jinou atmosféru podle toho, co uchovává. Někde jsou obrazy, jejichž oči se zdají sledovat člověka déle, než je příjemné, jinde archeologické nálezy, osobní předměty zemřelých, církevní artefakty nebo věci vyzvednuté z míst, kde se stalo něco násilného nebo nevysvětlitelného. Noční muzeum je plné odlesků ve skle, tlumených zvuků ventilace, kroků, které se vracejí ozvěnou, a stínů, v nichž se vitríny a figuríny mění v cosi nečekaně lidského.`,

  '5': `Mlha na polích se objevuje brzy ráno nebo pozdě večer, když se krajina ponoří do ticha a vše známé ztratí své pevné obrysy. Pole sama o sobě nejsou ničím výjimečná; pásy hlíny, obilí, trávy, remízky, polní cesty a vzdálené linie stromů působí za normálních podmínek obyčejně, téměř nudně. Právě proto je tak silné, když se přes ně převalí hustá bílá vrstva, která pohltí vzdálenosti, umlčí horizont a promění otevřený prostor v něco uzavřeného a nejistého.

V mlze se zvuky šíří zvláštně; kroky jsou tlumené, vzdálený pes nebo motor traktoru zní jinak, a člověk má pocit, že slyší pohyb tam, kde nic nevidí. Stromy u cest se mění v tmavé obrysy, sloupy elektrického vedení vypadávají z prostoru jako osamělé značky a každá známá polní cesta náhle působí delší a méně jistě. Na polích v mlze není nic výslovně nadpřirozeného, a právě proto je ten obraz tak silný; člověk neví, jestli zahlédl jen stín, osamělý strom, nebo něco, co tam stálo už dávno před ním.`,

  '6': `Panelákové sklepy působí na první pohled jako úplně obyčejná součást domu, kterou člověk zná z dětství i dospělosti — řady laťkových kójí, staré dveře, beton, trubky a slabé žárovky v dlouhých chodbách bez oken. Právě jejich obyčejnost je na nich nejznepokojivější, protože nic v nich není původně stavěné pro krásu, jen pro odložení věcí, které už nahoře překážejí. Stěny jsou vlhké, místy oprýskané, podlaha nese stopy letitého používání a ve vzduchu se drží směs prachu, starého dřeva, zatuchliny, kovu a něčeho sklepnatě chladného, co se nedá úplně pojmenovat.

Světlo zde nikdy nepůsobí dostatečně silně. I když žárovky fungují, mezi jednotlivými kužely světla zůstávají úseky, kde je šero příliš husté a kde se obyčejné předměty mění v neurčité tvary. Ze stropu vedou trubky, kabely a ventilační šachty, v rozích jsou odstavená kola, staré kočárky, zavařeniny, vyřazený nábytek a krabice, které už možná nepatří nikomu, kdo v domě ještě žije. Panelákové sklepy tak nepůsobí jako jedno místo, ale jako vrstva pod každodenním životem, kam se odkládají nejen věci, ale i něco z atmosféry domu samotného.`,

  '7': `Zastávka posledního autobusu bývá ve dne úplně nevýrazná — přístřešek z plastu a kovu, jízdní řád, lavička, odpadkový koš, reklamní panel a světlo pouliční lampy, které se rozsvěcí až večer. Jakmile se ale město nebo okraj obce ponoří do nočního klidu a provoz zeslábne, začne takové místo působit jinak, než by mělo. Prostor kolem zastávky je najednou příliš prázdný, silnice příliš dlouhá a ticho mezi jednotlivými zvuky příliš hluboké.

V noci se všechno soustředí na očekávání pohybu, který nepřichází nebo přichází později, než má. Ve skle přístřešku se odráží jen části okolí, světlo lampy kreslí ostré stíny a mokrý asfalt po dešti vypadá jako temná hladina. Občas projede auto, někde v dálce štěkne pes, ale jinak je zastávka jen bodem v prostoru, kde člověk čeká a zároveň cítí, že čekání samotné má zvláštní váhu. Když se nakonec v dálce objeví světla, nemusí hned přinést úlevu; naopak v sobě nesou nervozitu, protože v takové hodině už člověk nevěří úplně ani známým věcem, jako je autobus přijíždějící ze tmy.`,

  '8': `Městský hřbitov bývá sevřený mezi běžnou zástavbou, rušnými ulicemi nebo staršími domy, a právě proto působí tak zvláštně; je to kus ticha vložený doprostřed života, který kolem něj dál bez přestání pokračuje. Za kamennou zdí nebo litinovou branou se najednou otevře úplně jiný svět: úzké cesty, náhrobky, stromy, květiny, lucerny a řady jmen, která kdysi někomu znamenala celý vesmír. Starší části hřbitova bývají hustší, zarostlejší a tišší, s mechem na kameni, rozpukanými deskami, nakřivo posazenými kříži a rodinnými hrobkami, jejichž dveře vypadají, jako by je už dlouho nikdo neotevřel.

Přes den působí hřbitov klidně a důstojně, ale za šera nebo za nízké oblačnosti se jeho atmosféra mění. Stromy šumí jinak než v parku, kroky se mezi kameny rozléhají dutěji a i malý plamínek kahanu dokáže přitáhnout pozornost víc, než by člověk čekal. Čerstvé květiny vedle dávno neudržovaných hrobů, fotografie tváří za sklem, oprýskaná písmena a staré lampy vytvářejí dojem, že čas zde neplyne souvisle, ale ve vrstvách.`,

  '9': `Kaple u silnice stojí obvykle tam, kde by ji člověk téměř přehlédl — u krajské cesty, na okraji pole, u lesního úseku nebo poblíž zatáčky, kde auta projíždějí bez většího zájmu. Je malá, prostá a stará, postavená z kamene nebo omítaného zdiva, se střechou, která už mnohokrát vzdorovala dešti, sněhu i větru. Někdy má mříž, za níž je vidět svatý obraz nebo soška, jindy jen dřevěná dvířka, malý kříž a pár zbytků svíček, květin nebo stužek zanechaných lidmi, kteří se tu zastavili z důvodů, které nejsou zvenčí patrné.

Ve dne působí kaple jen jako drobná součást krajiny, tichá a téměř zapomenutá. K večeru nebo v noci ale začíná její přítomnost působit silněji, protože stojí sama v otevřeném prostoru a její malý objem světla, pokud v ní nějaké je, má v okolní tmě mnohem větší váhu. Vítr kolem ní zní ostřeji, traviny a větve se pohybují nervózněji a i moderní svět okolo — asfalt, auta, lampy, telefonní signál — jako by na pár metrů ustupoval něčemu staršímu.`,

  '10': `Opuštěná nemocnice je jedním z těch míst, která si i po vyklizení uchovávají silný otisk lidské přítomnosti, protože v jejích zdech se odehrávalo příliš mnoho bolesti, naděje, strachu i čekání na to, aby se prostor dokázal stát pouhou prázdnou budovou. Zvenčí může působit jen jako zanedbaný objekt — velké bloky oken, oprýskaná fasáda, zarostlé okolí, opuštěné parkoviště a vstupy přelepené zákazovými páskami nebo zajištěné plechem. Jakmile se ale člověk dostane dovnitř, vše získá jinou sílu: dlouhé chodby, sesterny, ordinace, čekárny, lůžková oddělení a sály mají zvláštní sterilní prázdnotu, která se nedá srovnat s žádnou jinou opuštěnou stavbou.

Barva se loupe ze zdí, podlahy nesou stopy koleček nemocničních lůžek, ve vzduchu se stále může držet slabý pach dezinfekce promíšený s plísní, prachem a stojatým vzduchem. Světlo sem vstupuje rozbitými okny nebo úzkými pruhy ze zanesených skel a dopadá na opuštěné vozíky, skříně, cedule, staré dokumentace, prázdné rámy lůžek a techniku, která už nefunguje, ale stále vypadá, jako by na něco čekala. Každý zvuk se zde vrací jinak — kapání, kroky, zavrzání dveří nebo vzdálený pád předmětu zní příliš ostře a příliš osaměle.`,

  '11': `Staré sídliště působí ve dne jako zcela běžný kus města, tvořený řadami panelových domů, malými obchody, dětskými hřišti, parkovišti a úzkými pruhy zeleně mezi betonem. Všechno je známé, opakující se a trochu unavené — stejné vchody, stejné balkony, stejná okna, za nimiž se večer rozsvěcují životy lidí, kteří se navzájem často znají jen od vidění. Právě ta opakovanost ale dává sídlišti zvláštní sílu, protože v takovém prostředí stačí drobná odchylka a člověk ji okamžitě cítí.

Večer a v noci se mezi domy drží zvláštní duté ticho, přerušované vzdálenou televizí, výtahem, psím štěkotem nebo kroky na schodišti. Lampy osvětlují jen části prostoru, takže dětská prolézačka, lavička nebo prázdné pískoviště začnou působit podivněji, než by měly. V některých oknech se stále svítí, jiná zůstávají dlouhodobě tmavá, a člověk má pocit, že celé sídliště sleduje samo sebe skrze stovky skel.`,

  '12': `Městský park po dešti vypadá jinak než za běžného dne; jako by voda na pár hodin smyla rutinu a odhalila tišší, starší podobu místa. Cesty jsou tmavší, lavičky lesklé, tráva sytější a mezi stromy visí vlhký vzduch, který tlumí hluky města a dává prostoru téměř uzavřený charakter. Kaluže zachycují světla lamp, odrazy větví a oblohy, ale někdy působí hlubší, než by měly, jako by v sobě držely jiný obraz, než jaký je kolem nich.

V parku po dešti se všechno zpomalí. Lidé zmizí rychleji než obvykle, ptáci utichnou a zvuk kapek dopadajících z listí na zem nebo na kovové zábradlí získá zvláštní rytmus. Stromy a keře působí tmavší, stezky delší a jednotlivá zákoutí oddělenější, protože mlha nebo vlhký opar rozostří vzdálenější obrysy. Takový park není vyloženě nebezpečný, spíš nečekaně cizí; jako místo, které je pořád veřejné a známé, ale po dešti si na krátký čas vezme kus svého prostoru zpátky a přestane být úplně lidské.`,

  '13': `Podchod pod nádražím je prostor, který má sloužit jen k rychlému průchodu, a právě tím je tak silný — nikdo v něm nechce zůstávat déle, než musí. Stěny jsou polepené starými reklamami, novými vrstvami plakátů, graffiti a šmouhami od letitého provozu, světlo bývá příliš bílé nebo naopak zažloutlé a vzduch těžký směsí vlhka, prachu, moči, kovu a proudícího města nad hlavou. Každý zvuk se zde násobí a vrací ozvěnou, takže kroky, kašel, vzdálený vlak nebo útržek cizího hlasu zní blíž a naléhavěji, než ve skutečnosti jsou.

Podchod je plný pohybu jen v určitých hodinách, ale mimo špičku se promění v nepříjemně prázdný tunel, v němž je všechno až příliš vidět a zároveň ne dost. Zatáčky, slepé výklenky, schodiště vedoucí nahoru i dolů, automaty, zamčené dveře a technické místnosti vytvářejí dojem prostoru, který má více vrstev, než připouští jeho jednoduchá funkce. Vlhkost stékající po stěnách a špinavé odlesky na dlaždicích dělají z podchodu místo, kde se i obyčejný stín nebo nehybná postava na konci chodby mohou zdát znepokojivější, než je rozumné.`,

  '14': `Studentská kolej je na první pohled hlučné, přechodné místo plné mladých lidí, věcí nahromaděných v malém prostoru a životů, které se tu na pár let potkají, než se zase rozutečou jinam. Chodby bývají dlouhé, pravidelné, s řadami stejných dveří, nástěnek, hasicích přístrojů, společných kuchyněk a koupelen, které nesou stopy neustálého používání. Ve dne je kolej živá, chaotická a téměř přecpaná energií, ale v noci se její atmosféra mění mnohem víc, než by člověk čekal.

Po půlnoci se ruch stáhne za zavřené dveře pokojů a zůstane jen bzučení zářivek, vzdálená hudba, tekoucí voda v potrubí a kroky někoho, kdo jde chodbou příliš pomalu. V takovém prostoru začne být velmi citelné, kolik různých lidí tu za léta bydlelo, hádalo se, milovalo, selhávalo, bálo se a nechávalo po sobě drobné stopy, které se nikdy úplně nevytratily. Společné prostory působí v noci odosobněněji než přes den, jako kulisy čekající na návrat hlasů, které jim dávají význam.`,

  '15': `Antikvariát bývá skrytý v užší ulici, v přízemí staršího domu nebo ve vnitrobloku, kam člověk nezabloudí náhodou příliš často. Výloha bývá zaplněná knihami, zažloutlými obálkami, starými mapami, pohlednicemi, rytinami a drobnostmi, které působí, jako by se do ní ukládaly po desetiletí bez větší snahy o modernizaci. Už při vstupu je patrná jiná hustota prostoru; regály stojí těsně u sebe, knihy jsou naskládané v policích, na stolech i na zemi a celé místo působí, jako by bylo složené z papíru, prachu, ticha a času.

Vzduch v antikvariátu má svou vlastní vůni — směs starého papíru, lepidla, tiskařské barvy, dřeva a jemné zatuchlosti, která nepůsobí odpudivě, ale naopak téměř uklidňujícím dojmem. Světlo sem proniká tlumeně, často přes zašlá skla nebo lampy s teplým odstínem, takže hřbety knih vrhají měkké stíny a rohy obchodu zůstávají trochu nejasné. Některé svazky vypadají, jako by je dlouho nikdo nevzal do ruky, jiné jsou zjevně přesouvané častěji, a člověk má pocit, že pořádek v nich zná jen ten, kdo tu tráví roky života.`,

  '16': `Vlakové nádraží za svítání působí jako místo mezi dvěma stavy světa — noc už skončila, ale den ještě nezačal naplno. Perony, koleje, podchody, čekárny a odjezdové tabule jsou stále stejné jako během dne, ale v tuto hodinu jsou zahalené do studeného světla, vlhkého vzduchu a zvláštní únavy prostoru, který nikdy úplně nespí. Lampy ještě svítí, obloha je bledá a kovové konstrukce, lavičky i okraje nástupišť vypadají tvrději, syrověji a osaměleji než v plném provozu.

Zvuky zde mají jinou váhu než přes den. Hlášení z reproduktorů zní dutěji, vzdálený příjezd vlaku je slyšet dlouho předtím, než se objeví, a kroky několika cestujících se rozléhají po peronu téměř nepřirozeně jasně. Lidé, kteří se zde v tuhle hodinu pohybují, působí jako postavy na přechodu — unavení, mlčenliví, ponoření do vlastních myšlenek, jako by sem nepatřili úplně oni ani jejich cíle.`,

  '17': `Přehrada působí na první pohled jako technická stavba, pevná, rozumná a postavená proto, aby zkrotila vodu a dala jí řád. Betonová hráz, zábradlí, servisní cesty, věže, schodiště a hluboká vodní plocha vytvářejí obraz lidské kontroly nad krajinou, ale právě pod touto strohostí se skrývá její zvláštní síla. Hladina bývá klidná a široká, často až příliš tichá, a okolní lesy, kopce nebo mlha jí dávají téměř nehybný, zatajený výraz.

Člověk si při pohledu na přehradu vždy uvědomuje, že pod vodou leží něco, co tam kdysi nebylo skryté — staré cesty, základy domů, stromy, možná celá vesnice nebo alespoň kus krajiny, který zmizel, aby vzniklo tohle nové jezero. Vítr tu zní jinak než na běžné vodě, hlasy se nesou daleko a i obyčejné šplouchnutí působí hlubší, než by mělo. Za zataženého dne nebo navečer působí přehrada téměř bezčasově, jako místo, které člověk sice vytvořil, ale nedokázal úplně ovládnout jeho paměť.`,

  '18': `Zapomenuté kino stojí v části města, kde už lidé chodí spíš kolem než dovnitř, a působí jako schránka pro dobu, která se odmítla úplně rozpadnout. Fasáda bývá oprýskaná, plakátové vitríny prázdné nebo plné starých vrstev papíru, písmena názvu neúplná a vchod zavřený, jako by se poslední promítání odehrálo už dávno a nikdo přesně nevěděl kdy. Přesto si budova drží svůj zvláštní charakter; i opuštěná stále vypadá jako místo určené pro obrazy, hlasy a cizí příběhy.

Uvnitř bývá předsálí s pokladnou, těžkými dveřmi, zbytky koberců, plakátů a vůní starého prachu, látky a elektriky. Sál samotný působí jako prostor, kde čas ztuhl — řady sedadel, plátno, balkon, promítací kabina a stěny uzpůsobené akustice stále čekají, jako by se měl film znovu spustit. Ticho zde není obyčejné, protože je to ticho místa, které bylo kdysi určené pro kolektivní prožívání emocí, smíchu, strachu a dojetí.`,

  '19': `Střecha obchodního centra bývá jedním z těch míst, o nichž většina lidí ví, že existují, ale téměř nikdo je vlastně nevidí. Pod ní je svět výloh, hudby, jídla, lidí, reklamy a nepřetržitého konzumu, zatímco nahoře se rozprostírá technický, větrný a nečekaně prázdný prostor plný klimatizačních jednotek, servisních cest, antén, potrubí a betonových ploch. Z výšky je vidět okolní město jinak — parkoviště, silnice, světla, střechy dalších budov — ale samotná střecha působí odříznutě, jako zapomenutá vrstva moderního světa.

Večer nebo v noci získává tohle místo zvláštní atmosféru. Hluk zespodu už doléhá jen tlumeně, vítr je silnější, světla města se odrážejí na kovových površích a člověk má pocit, že stojí nad něčím velmi živým, ale sám je mimo jeho rytmus. Technické prvky — ventilátory, výdechy, servisní dveře, výstražné značky — působí v takové chvíli téměř anonymně, jako součást mechanismu, který nikdo běžně nesleduje.`,

  '20': `Les za satelitním městečkem začíná často nenápadně — za poslední řadou nových domů, plotů, zahrad, dětských trampolín a pečlivě střižených trávníků se najednou zvedne linie stromů, která působí mnohem starší než vše kolem. Kontrast mezi novotou ulic, aut, fasád a bezpečnostních kamer na jedné straně a nepravidelností lesa na straně druhé je velmi silný. Tam, kde končí asfalt a upravené parcely, začíná prostor bez přímých linií, bez lidské kontroly a bez okamžité čitelnosti.

Les sám nemusí být nijak divoký v romantickém smyslu, ale právě jeho obyčejná skutečnost je zneklidňující. Stromy stojí těsněji, než by se z dálky zdálo, světlo mezi nimi rychle slábne, zem je plná kořenů, listí, starých větví a stop po něčem, co zde bylo dávno před developerským plánem. Zvuky z městečka sem ještě chvíli doléhají — sekačky, hlasy, auto, pes — ale brzy se ztratí a les si vezme vlastní ticho. Tento typ lesa působí jako připomínka, že moderní svět se rozšířil jen po určitý okraj a za ním stále čeká něco staršího, trpělivějšího a mnohem méně ochotného nechat se pojmenovat.`,
};

export default MYSTIC_DESCRIPTIONS;
