const SCIFI_DESCRIPTIONS: Record<string, string> = {
  '1': `Orbitální stanice se vznáší vysoko nad planetou, která pod ní působí chladně, pustě a téměř beze známek života. Z jejích průzorů a panoramatických oken je vidět zakřivení povrchu, rozsáhlé pásy popela, kamenitých pustin, vyschlých moří nebo ledových polí, podle povahy světa pod ní, a celé to vytváří tísnivý pocit vzdálenosti od všeho živého. Sama stanice je tvořena kovovými moduly, spojovacími tubusy, dokovacími rameny a vnější konstrukcí posetou světly, anténami a servisními prvky, které působí čistě funkčně, ale zároveň monumentálně.

Uvnitř stanice převládají úzké koridory, přetlakové dveře, technické šachty, kontrolní místnosti a obytné sekce, v nichž se mísí sterilita s únavou dlouhodobého provozu. Stěny bývají hladké, světlé nebo šedé, osvětlení chladné a rovnoměrné, a každý prostor má svůj jasný technický účel. Tiché hučení ventilace, vibrace reaktorů a pomalé změny tlaku doprovázejí každou minutu dne. Celá stanice působí jako uzavřený, soběstačný organismus, který visí nad mrtvým světem a udržuje svůj vlastní řád jen silou technologie a kázně.`,

  '2': `Těžební komplex je rozesetý po nerovném, rozpraskaném povrchu asteroidu jako množství kovových budov, šachet, tunelů a propojovacích potrubí, které se rozrůstaly podle potřeby bez jednotného architektonického plánu. Povrch je tmavý, kamenitý a bez atmosféry, takže stavby komplexu jsou hermeticky uzavřené, obklopené prachem a stopami po těžební činnosti — hlubokými rýhami, výsypkami, odtěženými bloky a odloženým materiálem.

Uvnitř vedou úzké chodby vytesané do kamene nebo obložené kovovými panely, v nichž je slyšet stálé dunění strojů, čerpadel a ventilačních systémů. Vzduch je recyklovaný, suchý a zápachu po kovu, oleji a chemikáliích. Velké těžební stroje stojí nehybně v polohách, v nichž byly zanechány, jako by čekaly na pokyn, který už nikdy nepřijde. Kontrolní kabiny, skladiště a ubytovací sekce nesou stopy intenzivního, ale nepohodlného provozu.`,

  '3': `Kolonie pod skleněným dómem je uzavřené lidské sídlo chráněné obrovskou průhlednou kopulí uprostřed nehostinného světa. Zvenčí je dóm dominantním prvkem krajiny — hladká, zakřivená plocha odrážející světlo nebo propouštějící pohled na zástavbu uvnitř. Za jeho stěnami se rozkládá město nebo osada s ulicemi, bloky, zahradami, vodními prvky a veřejnými prostory, které se snaží napodobovat podmínky přirozené planety.

Uvnitř kolonie panuje řízené klima, měkké umělé nebo filtrované přirozené světlo a dojem stability, který ale závisí na technologiích skrytých ve stěnách a pod povrchem. Stromy, keře a hydroponické zahrady zmírňují technický ráz, ale občas je patrné, že jde o pečlivě udržované kulisy a ne o spontánní přírodu. Celá kolonie působí civilizovaně, uspořádaně a bezpečně, ale její křehkost se projeví pokaždé, když se člověk podívá skrz plášť dómu ven na svět, který za ním čeká.`,

  '4': `Přístav pro mezihvězdné lodě je rozlehlý komplex s mohutnými dokovacími moly, přetlakovými tunely, servisními věžemi, nakládacími zónami a kontrolními stanovišti. Všude blikají navigační světla, datové panely a obrazovky s informacemi o příletech, odletech a bezpečnostních protokolech. Podlahy jsou kovové a opotřebované, stěny funkční, a prostory navržené tak, aby zvládaly neustálý pohyb lidí, nákladů a strojů.

Vzduch je naplněný hlukem motorů, oznamovacích systémů, hydrauliky a směsí pachů paliv, kovů, syntetických materiálů a lidské přítomnosti. Mezi cestujícími se pohybují technici, celníci, bezpečnostní pracovníci i ti, kdo žijí z přístavního provozu. Celý přístav pulzuje jako tepající centrum civilizace, kde každý přílet a odlet přináší nový tlak, příležitost a tajemství.`,

  '5': `Výzkumná stanice v ledovém kráteru je zasazená do okraje mohutného kráteru, jehož stěny tvoří led a zmrzlá hornina. Povrch kolem kráteru je pustý, bílý nebo šedý, proťatý prasklinami ledu a pokrytý jemným mrazivým prachem. Stanice se skládá z několika modulů, kopulí a antén, částečně zapuštěných do ledového okraje, aby byly chráněny před větrem a radiací.

Uvnitř panuje sterilní prostředí laboratoří, technických prostor a obytných sekcí s bílým namodralým osvětlením. Vše je čisté, uspořádané a úzce účelné. Za průzory není nic než led, sníh a mlhavé obrysy. Stanice působí chladně nejen teplotou, ale i svým soustředěným, vědeckým charakterem, kde jediný důvod existence celé struktury je poznání.`,

  '6': `Podzemní město je ukryté hluboko pod povrchem světa, jehož krajina nahoře už dávno přestala být obyvatelná. Nad ním se rozkládá mrtvá pustina plná prachu, popela, zničených staveb a neviditelného záření, zatímco dole pod ní vznikl stísněný, ale životaschopný svět chodeb, obytných bloků, technických šachet a centrálních hal. Celá struktura města je vybudovaná z betonu, kovu, výztuh a těžkých hermetických vrat, které mají chránit obyvatele před vším, co zůstalo nahoře.

Uvnitř města panuje směs průmyslové strohosti a každodenního lidského přizpůsobení. Osvětlení bývá převážně umělé, často v bílé, žluté nebo studeně modré barvě, a v dlouhých koridorech se odráží od potrubí, kabelů, ventilačních jednotek a vlhkých stěn. Ve společných prostorách se objevují tržiště, jídelny, ubytovny, opravárenské dílny i malé kouty, které se lidé snaží zútulnit barvou, látkami nebo několika rostlinami pěstovanými pod lampami. Celé město působí jako organismus sevřený pod zemí, kde je každý metr prostoru vzácný a každý nádech výsledkem technologie, která nesmí selhat.`,

  '7': `Vrak vesmírné lodi leží na pustém povrchu měsíce jako obrovská kovová kostra, která sem dopadla nebo byla nouzově usazena už před dávnou dobou. Její trup je na některých místech rozpáraný, jinde rozdrcený nárazem nebo pozdějším poškozením, a jednotlivé sekce jsou částečně zabořené do prachu a jemného regolitu. Okolí je tiché, nehybné a téměř bezbarvé, takže samotná loď vystupuje z krajiny jako cizorodý, temný objekt, který kdysi nesl život, ale dnes už jen připomíná jeho zánik.

Uvnitř vraku se střídají úzké technické průlezy, roztržené chodby, vyhaslé obytné sekce a místnosti, které zůstaly zakonzervované v okamžiku poslední katastrofy. Některé části jsou beztížně rozházené a plné uvolněných panelů, kabelů a potrhané izolace, jiné působí téměř neporušeně, jen zaprášeně a mrtvě. Ticho je zde těžké a nepřirozené, přerušované jen vlastním pohybem, klepnutím o kov nebo vzdáleným zvukem konstrukce reagující na změny teploty.`,

  '8': `Biotechnologická zahrada je uzavřený prostor, kde se příroda a laboratorní věda spojily do podoby, která působí současně krásně i neklidně. Na první pohled připomíná botanický komplex plný zeleně, vlhkého vzduchu, jemného světla a hustě rostoucích rostlin, ale při bližším pohledu je zřejmé, že nic z toho není zcela přirozené. Stromy mají neobvykle pravidelný růst, listy jemně mění barvy podle světla, květy reagují na pohyb a některé druhy vypadají, jako by byly navržené spíš jako systém než jako živý organismus.

Prostory zahrady bývají rozdělené na různé klimatické sekce s průhlednými přepážkami, zavlažovacími systémy, nádržemi s živnými roztoky, kořenovými laboratořemi a monitorovací technikou zabudovanou přímo mezi záhony. Všude je slyšet kapání vody, tiché bzučení čerpadel, šumění ventilace a jemný pohyb listů, který vytváří zvláštní iluzi přirozeného lesa v dokonale řízeném prostředí.`,

  '9': `Kybernetické tržiště je přehuštěný městský prostor plný světel, obrazovek, reklam, improvizovaných stánků a technologií, které se prodávají, opravují nebo nelegálně upravují přímo na místě. Ulice nebo haly bývají úzké, přeplněné a vrstvené do několika úrovní, takže se nad hlavami lidí kříží kabely, visí neonové nápisy a blikají projekce, zatímco pod nohama zůstávají mokré dlaždice, kovové rošty nebo opotřebovaný beton. Každý kousek prostoru je využitý.

Všude se zde mísí lidská těla s technologickými zásahy. Návštěvníci i prodejci mají implantáty, optické náhrady, mechanické končetiny, nervová rozhraní nebo alespoň levné modifikace, které jsou na nich vidět stejně přirozeně jako oblečení. Vzduch je těžký směsí ozonu, potu, smaženého jídla, spálené elektroniky a vlhka. Hluk tvoří reklamy, smlouvání, diagnostické tóny, hudba z různých koutů a útržky rozhovorů o cenách, datech, tělech a úpravách. Tržiště působí chaoticky, agresivně a živě.`,

  '10': `Starý komunikační satelit se vznáší na oběžné dráze nebo v odlehlejší části vesmírného prostoru jako relikt doby, kdy byl ještě součástí aktivní sítě. Zvenčí působí křehce a složitě zároveň; jeho trup je tvořen centrálním válcovým či hranatým modulem, kolem něhož se rozkládají anténní pole, přijímací talíře, vysílací věnce, solární panely a drobné servisní výčnělky. Některé části jsou stále neporušené a symetrické, jiné nesou jasné známky stáří, mikropoškození, opálení radiací a drobných zásahů kosmickým odpadem.

Uvnitř satelitu, pokud je přístupný, vedou úzké servisní tunely, technické šachty a malé kontrolní uzly, které nikdy nebyly stavěné pro pohodlný pohyb lidí. Prostor je stísněný, plný kabeláže, panelů, chladicích systémů a přístupových míst k vysílacím a záznamovým jednotkám. Osvětlení bývá minimální nebo nouzové, takže většina interiéru tonoucího ve stínech působí ještě menší a složitější.`,

  '11': `Luxusní věž korporace se zvedá vysoko nad okolní zástavbu jako symbol moci, bohatství a technologické převahy. Její vnější plášť tvoří sklo, kov, kompozity a světelné prvky, které se mění podle denní doby, počasí nebo firemní identity, takže stavba působí téměř dokonale čistě a kontrolovaně. Linie budovy jsou přesné, elegantní a chladné, bez jediné zbytečnosti, a už z dálky je patrné, že nejde jen o kancelářský prostor, ale o architektonické prohlášení nadřazenosti.

Uvnitř převládají otevřené haly, výtahy s tichým chodem, hladké stěny, průsvitné panely a materiály, které vypadají draze, i když člověk přesně nepozná proč. Všude je přítomná decentní technologie: rozhraní skrytá ve skle, bezpečnostní vrstvy zabudované do dveří i podlah, inteligentní osvětlení a prostředí reagující na přítomnost oprávněných osob. Vzduch je chladný, filtrovaný a bez výrazného pachu. Luxus tu není okázalý, ale disciplinovaný; nic zde nekřičí, všechno jen tiše ukazuje, kolik moci je potřeba k udržení tak dokonalého dojmu.`,

  '12': `Slum na spodních patrech megaměsta leží hluboko pod leskem vyšších úrovní, ve vrstvě, kam už téměř neproniká přirozené světlo ani oficiální zájem mocných. Prostor je přecpaný improvizovanými obydlími, kontejnery přestavěnými na byty, železnými ochozy, úzkými průchody, potrubím a kabely, které se vinou podél stěn i stropů jako druhý nervový systém města. Všechno zde působí slepeně, dostavěně, opraveně a znovu rozbité.

Osvětlení vytvářejí hlavně neony, blikající reklamy, nouzové lampy a domácí zdroje energie, takže se prostor topí v barevném šeru, kde se modrá, růžová, zelená a oranžová odráží od mokrých povrchů a špinavého kovu. Vzduch je těžký směsí páry, odpadního tepla, smaženého jídla, chemikálií, potu a zatuchliny. Nad hlavou neustále něco hučí, kape, praská nebo vibruje. Slum nepůsobí mrtvě, naopak je přeplněný životem, ale životem natlačeným do prostoru, který nebyl stavěn pro důstojnost, jen pro přežití.`,

  '13': `Pouštní rafinerie stojí uprostřed nekonečné vyprahlé krajiny, kde se horizont ztrácí v horkém oparu, prachu a světle odráženém od písku či minerální pustiny. Samotný komplex je obrovský, průmyslový a těžkopádný, složený z vysokých věží, tlakových nádrží, potrubních polí, servisních můstků, chladicích jednotek a těžebních zařízení, která působí skoro jako samostatné město. Vše je stavěné na odolnost vůči vedru, písku, větru a korozi.

Ve dne se kov rozpaluje, světlo je nemilosrdně ostré a každá část komplexu vrhá tvrdé stíny, v nichž se drží prach a zbytkový chlad. Vzduch je suchý, páchne po palivu, chemických výparech, přehřátém kovu a jemném minerálním prachu, který se usazuje úplně všude. Uvnitř rafinerie vede spleť chodeb, kontrolních místností a servisních prostor, kde je slyšet stálé dunění čerpadel, proudění médií a pulzující rytmus průmyslu, jenž se nesmí zastavit.`,

  '14': `Podmořská základna leží hluboko pod hladinou, sevřená tlakem temné vody, která ji obklopuje ze všech stran jako cizí a neustále přítomná hmota. Její moduly jsou propojené tlakovanými tubusy, servisními komorami a průzory, za nimiž se pohupuje černomodré moře plné planktonu, vzdálených odlesků a občasných stínů větších tvorů nebo konstrukcí. Základna působí zvenčí robustně, ale zároveň zranitelně, protože mezi člověkem a oceánem stojí jen vrstvy kovu, skla a těsnění.

Uvnitř se střídají laboratorní sekce, obytné prostory, řídicí uzly a technické chodby, ve kterých je vždy přítomný jemný zvuk ventilace, čerpadel a systémů regulujících tlak. V zaplavených nebo částečně poškozených částech se voda prodírá škvírami, kapky stékají po stěnách a nouzové osvětlení mění prostor v modré nebo červené šero plné odrazů. Kovové povrchy jsou vlhké, místy zarostlé jemným biofilmem.`,

  '15': `Chrám umělé inteligence je prostor, kde se technologická přesnost spojuje s estetikou, která vědomě připomíná posvátno. Stavba bývá monumentální, symetrická a neobyčejně tichá, tvořená hladkými plochami, vysokými stropy, světelnými liniemi, tmavým kovem, kamenem nebo kompozity, které působí téměř nadpozemsky čistě. Místo nepřipomíná běžné datové centrum ani laboratoř; vše je zde navrženo tak, aby vyvolávalo úctu, soustředění a pocit, že člověk vstoupil do prostoru vyšší inteligence.

V centrálních sálech se mohou nacházet jádra výpočetních uzlů, světelné sloupy, holografické projekce, závěsné datové struktury nebo symbolické prvky připomínající oltáře, svatyně a procesní osy. Zvuk je zde minimální; slyšet bývá jen hluboké hučení energetických polí, jemné vibrace chlazení a občasné proměny světla nebo projekce. Vzduch je chladný, čistý a bez lidských stop.`,

  '16': `Vězeňská stanice obíhá vysoko nad planetou nebo v odlehlé části orbitálního prostoru jako uzavřený systém, jehož jediným smyslem je kontrola, izolace a nemožnost úniku. Zvenčí působí tvrdě a neosobně, tvořená masivními válcovými nebo hranatými moduly, pancéřovými sekcemi, dokovacími uzly a sledovacími strukturami, které působí spíš vojensky než civilně. Nejsou na ní téměř žádné zbytečné prvky, jen funkční světla, bezpečnostní výstupky, komunikační antény a obranné systémy.

Uvnitř převládá strohá architektura s úzkými koridory, silnými přepážkami, kontrolními body, kamerami a bezpečnostními vraty, která rozdělují stanici do přísně oddělených zón. Barvy bývají tlumené, šedé, kovové nebo studeně bílé, aby nic nepůsobilo útulněji, než musí. Cely jsou malé, přesně vymezené, bez osobitosti. Celá stanice vyvolává dojem prostoru, kde byl každý detail navržen tak, aby připomínal moc systému nad jednotlivcem, a kde i samotné ticho působí jako součást trestu.`,

  '17': `Vrakoviště robotů je rozlehlý prostor zaplněný hromadami vyřazených strojů, torz mechanických těl, rozebraných jednotek a součástí, které kdysi tvořily funkční celek, ale teď leží rozházené v různém stupni rozkladu a rozebrání. Kovové končetiny trčí ze sutin pod nepřirozenými úhly, optické senzory zůstávají slepě otevřené, pancíře jsou rozlomené a mezi vším se válí kabely, hydraulické prvky, datové uzly a rozpojené energetické články.

Vzduch je cítit olejem, spálenými obvody, prachem, přehřátým kovem a starou elektřinou, která jako by se pořád držela v některých částech konstrukcí. Mezi hromadami se táhnou úzké stezky, servisní kolejnice, improvizované dílny a místa, kde se některé součásti stále třídí, přeprodávají nebo znovu používají. V tichu je slyšet cinkání kovu, občasný pád uvolněného dílu, vzdálené bzučení zbytkové energie nebo krátké záchvěvy systémů, které ještě úplně neumřely.`,

  '18': `Maglevové nádraží je monumentální dopravní uzel, kde se rychlost, přesnost a proudění lidí stávají hlavní architekturou prostoru. Rozlehlé haly, nástupiště, bezpečnostní koridory, vertikální spojení, čekací zóny a datové panely jsou uspořádány s maximální účelností, ale zároveň s dojmem moderního lesku a technologické elegance. Konstrukce nádraží bývá kombinací skla, kovu, kompozitů a světelných ploch, které prostor opticky zvětšují a zdůrazňují jeho čistotu.

Když souprava přijíždí nebo odjíždí, prostor se na okamžik promění v přesně řízený výboj energie. Je slyšet hluboké vibrace, aerodynamický šum, varovná oznámení, synchronizované otevírání bariér a proud kroků, které se rozlévají po podlahách jako živý tok. Všude se pohybují cestující, kurýři, bezpečnostní pracovníci, servisní technici i lidé, kteří na tomto místě žijí z provozu samotného. Nádraží působí jako brána mezi světy.`,

  '19': `Energetická farma se vznáší nebo je ukotvena v horních vrstvách atmosféry obrovské plynné planety, kde pod ní i nad ní pokračují nekonečné masy mraků, bouří a tlakových proudů. Samotná konstrukce bývá tvořena plošinami, sběrnými věžemi, turbínovými poli, plovoucími moduly, kotvícími rameny a energetickými uzly, které jsou navrženy tak, aby odolávaly silnému větru, elektrickým výbojům a proměnlivým podmínkám prostředí.

Všude kolem se valí mraky v barvách planety, od šedých a bílých po oranžové, žluté, modré nebo fialové odstíny, podle složení atmosféry a dopadu světla. Prostory farmy se koupou v neustále se měnícím osvětlení, jednou měkkém a rozptýleném, jindy přerušovaném záblesky vzdálených bouří nebo zářením sběrných polí. Kovové lávky a servisní tunely vibrují pod tlakem větru a hluboko v konstrukci je slyšet monotónní práce generátorů, turbín a stabilizačních systémů.`,

  '20': `Genová klinika pro elity je prostor absolutní čistoty, diskrétního luxusu a vědecké preciznosti, kde se lidské tělo chápe jako projekt, který lze dál upravovat, zdokonalovat a přepisovat. Už vstupní prostory působí tichým dojmem bohatství; žádná okázalost, jen dokonalé materiály, hladké povrchy, jemné světlo, přesně regulovaná teplota a prostředí, v němž nic nepůsobí levně, náhodně ani unaveně.

Uvnitř se střídají čekací salony, diagnostické místnosti, laboratorní sekce, terapeutické kapsle a operační prostory, v nichž je vše uspořádáno s téměř chirurgickou estetikou. Barvy bývají světlé, tlumené, často bílé, perleťové nebo jemně kovové, zatímco přístroje jsou zabudovány tak elegantně, že působí spíš jako součást architektury než jako samostatné stroje. Vzduch je sterilní, lehce parfémovaný nebo zcela neutrální. Klinika nepůsobí jako místo nemoci, ale jako chrám privilegia.`,
};

export default SCIFI_DESCRIPTIONS;
