import type { Theme } from '../../types';

export const sciFiTheme: Theme = {
  id: 'sci-fi',
  name: 'Sci-fi',
  scope: 'both',
  atmosphere: 'Civilní vesmírná stanice — cyan + magenta neon',
  vars: {
    '--bg-primary':       '#080c14',
    '--bg-secondary':     '#0c1220',
    '--bg-card':          '#0f1628',
    '--bg-card-hover':    '#141e32',
    '--accent':           '#00c8ff',
    '--accent-bright':    '#40d8ff',
    '--accent-dim':       '#006888',
    '--accent-soft':      'rgba(0, 200, 255, 0.15)',
    '--text-primary':     '#d0e8ff',
    '--text-secondary':   '#5090b0',
    '--text-muted':       '#2a4060',
    '--border':           '#0f2030',
    '--border-subtle':    '#0a1820',
    '--border-strong':    '#00c8ff',
    '--success':          '#3ecf8e',
    '--warning':          '#f5a623',
    '--danger':           '#f06060',
    '--info':             '#00c8ff',
    '--text-on-accent':       '#04101a',
    '--text-on-danger':       '#050508',
    '--bg-overlay':           'rgba(0, 8, 16, 0.7)',
    '--success-soft':         'rgba(62, 207, 142, 0.12)',
    '--success-soft-border':  'rgba(62, 207, 142, 0.4)',
    '--warning-soft':         'rgba(245, 166, 35, 0.12)',
    '--warning-soft-border':  'rgba(245, 166, 35, 0.4)',
    '--danger-soft':          'rgba(240, 96, 96, 0.12)',
    '--danger-soft-border':   'rgba(240, 96, 96, 0.4)',
    '--danger-focus-ring':    'rgba(240, 96, 96, 0.3)',
    '--font-logo':        '"Orbitron", "Exo 2", sans-serif',
    '--font-display':     '"Rajdhani", "Exo 2", sans-serif',
    '--font-body':        '"Inter", "Roboto", sans-serif',
  },
  fonts: {
    logo: 'Orbitron',
    display: 'Rajdhani',
    body: 'Inter',
  },
  thumbnail: '/themes/thumbnails/sci-fi.webp',
  background: '/themes/backgrounds/sci-fi.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'heavy',
};
