import type { Theme } from '../../types';

export const prirodaTheme: Theme = {
  id: 'priroda',
  name: 'Příroda',
  scope: 'both',
  atmosphere: 'Zakletý les — dřevo, smaragdové krystaly, sluneční paprsky',
  vars: {
    '--bg-primary':       '#1a1208',
    '--bg-secondary':     '#231a0a',
    '--bg-card':          '#2a1e0c',
    '--bg-card-hover':    '#332510',
    '--accent':           '#4a8a30',
    '--accent-bright':    '#68b040',
    '--accent-dim':       '#244818',
    '--accent-soft':      'rgba(74, 138, 48, 0.18)',
    '--text-primary':     '#e8d8a0',
    '--text-secondary':   '#987b46',
    '--text-muted':       '#504030',
    '--border':           '#4a3018',
    '--border-subtle':    '#2a1e0c',
    '--border-strong':    '#00c090',
    '--success':          '#68b040',
    '--warning':          '#d4900a',
    '--danger':           '#c04030',
    '--info':             '#4a8a30',
    '--text-on-accent':       '#071005',
    '--text-on-danger':       '#ffffff',
    '--bg-overlay':           'rgba(10, 8, 4, 0.65)',
    '--success-soft':         'rgba(104, 176, 64, 0.14)',
    '--success-soft-border':  'rgba(104, 176, 64, 0.4)',
    '--warning-soft':         'rgba(212, 144, 10, 0.14)',
    '--warning-soft-border':  'rgba(212, 144, 10, 0.4)',
    '--danger-soft':          'rgba(192, 64, 48, 0.14)',
    '--danger-soft-border':   'rgba(192, 64, 48, 0.4)',
    '--danger-focus-ring':    'rgba(192, 64, 48, 0.3)',
    '--font-logo':        '"Cinzel", "Uncial Antiqua", Georgia, serif',
    '--font-display':     '"IM Fell English", "Lora", Georgia, serif',
    '--font-body':        '"Lora", Georgia, serif',
  },
  fonts: {
    logo: 'Cinzel',
    display: 'IM Fell English',
    body: 'Lora',
  },
  thumbnail: '/themes/thumbnails/priroda.webp',
  background: '/themes/backgrounds/priroda.webp',
  decorationsModule: () => import('./decorations.css'),
  reducedMotion: 'safe',
};
